# This file is meant to be applied as overrides when running podman/docker
# with SELinux enabled. It adds docker file label overrides to volumes.
# It should be applied last with -f parameter.
# podman-compose -f compose.yaml -f compose.override.yaml -f compose.selinux.yaml up -d

services:
  solr:
    volumes:
      - ./conf/solr:/opt/solr/server/solr/configsets/olconfig:ro,z
  web:
    volumes:
      - .:/openlibrary:z
  fast_web:
    volumes:
      - .:/openlibrary:z
  solr-updater:
    volumes:
      - .:/openlibrary:z
  db:
    volumes:
      - .:/openlibrary:z
      - ./docker/ol-db-init.sh:/docker-entrypoint-initdb.d/ol-db-init.sh:z
  covers:
    volumes:
      - .:/openlibrary:z
  infobase:
    volumes:
      - .:/openlibrary:z
  home:
    volumes:
      - .:/openlibrary:z
