#!/usr/bin/env python
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

root = Path(__file__).resolve().parent
TYPES_PATH = root / "solr_types.py"
OVERRIDES = {
    "type": "Literal['work', 'author', 'subject']",
    "public_scan_b": "Optional[bool]",
    "printdisabled_s": "Optional[str]",
    "lending_edition_s": "Optional[str]",
    "ebook_count_i": "Optional[int]",
    "last_modified_i": "Optional[int]",
}


def generate():
    """This function generates the types.py file."""

    # read the managed-schema xml file
    solr_schema = ET.parse(root.parent.parent / "conf/solr/conf/managed-schema.xml")
    python_fields: list[str] = []
    seen_names: set[str] = set()
    for field in solr_schema.getroot().findall("field"):
        name = field.get("name")
        if name.startswith("_"):
            continue

        required = field.get("required") == "true"
        typ = field.get("type")
        multivalued = field.get("multiValued") == "true"
        type_map = {
            "pdate": "str",
            "pint": "int",
            "plong": "int",
            "string": "str",
            "text_en_splitting": "str",
            "text_general": "str",
            "text_international": "str",
            "boolean": "bool",
            "pfloat": "float",
        }

        if name in OVERRIDES:
            python_type = OVERRIDES[name]
        elif typ in type_map:
            python_type = type_map[typ]
        elif (field_type := solr_schema.find(f".//fieldType[@name='{typ}']")) is not None:
            field_class = field_type.get("class")
            if field_class == "solr.EnumFieldType":
                enumsConfigFile = field_type.get("enumsConfig")
                enumsConfig = ET.parse(root.parent.parent / "conf/solr/conf" / enumsConfigFile)
                enum_values = [el.text for el in enumsConfig.findall(f".//enum[@name='{field_type.get('enumName')}']/value")]
                python_type = f"Literal[{', '.join(map(repr, enum_values))}]"
            elif field_class == "solr.ICUCollationField":
                python_type = "bytes"
            else:
                raise Exception(f"Unknown field type class {field_class}")
        else:
            raise Exception(f"Unknown field type {typ}")

        if name not in OVERRIDES:
            if multivalued:
                python_type = f"list[{python_type}]"
            if not required:
                python_type = f"Optional[{python_type}]"

        seen_names.add(name)
        python_fields.append(f"    {name}: {python_type}")

    for key, value in OVERRIDES.items():
        if key not in seen_names:
            python_fields.append(f"    {key}: {value}")

    body = "\n".join(python_fields)
    python = f"""# This file is auto-generated by generate_solr_types.py
# To regenerate:
#   python openlibrary/solr/generate_solr_types.py
# fmt: off
# ruff: noqa: UP045
from typing import Literal, Optional, TypedDict


class SolrDocument(TypedDict):
{body}

# fmt: on"""

    return python


def main() -> int:
    """Regenerate solr_types.py in place; used as a pre-commit hook."""
    new_content = generate().strip() + "\n"
    old_content = TYPES_PATH.read_text()

    if new_content == old_content:
        return 0

    TYPES_PATH.write_text(new_content)
    sys.stderr.write(f"{TYPES_PATH} was out of date; regenerated it.\n")
    return 1


if __name__ == "__main__":
    sys.exit(main())
