# This file is auto-generated by types_generator.py
from __future__ import annotations

from typing import Literal, TypedDict


class SolrDocument(TypedDict):
    key: str
    type: Literal['work', 'author', 'subject']
    redirects: list[str] | None
    has_fulltext: bool | None
    title: str | None
    title_suggest: str | None
    subtitle: str | None
    alternative_title: list[str] | None
    alternative_subtitle: list[str] | None
    edition_count: int | None
    edition_key: list[str] | None
    cover_edition_key: str | None
    by_statement: list[str] | None
    publish_date: list[str] | None
    publish_year: list[int] | None
    first_publish_year: int | None
    first_edition: str | None
    first_publisher: str | None
    language: list[str] | None
    number_of_pages_median: int | None
    lccn: list[str] | None
    ia: list[str] | None
    ia_box_id: list[str] | None
    ia_loaded_id: list[str] | None
    ia_count: int | None
    oclc: list[str] | None
    isbn: list[str] | None
    lcc: list[str] | None
    lcc_sort: str | None
    ddc: list[str] | None
    ddc_sort: str | None
    contributor: list[str] | None
    publish_place: list[str] | None
    publisher: list[str] | None
    publisher_facet: list[str] | None
    first_sentence: list[str] | None
    author_key: list[str] | None
    author_name: list[str] | None
    author_alternative_name: list[str] | None
    author_facet: list[str] | None
    subject: list[str] | None
    subject_facet: list[str] | None
    subject_key: list[str] | None
    place: list[str] | None
    place_facet: list[str] | None
    place_key: list[str] | None
    person: list[str] | None
    person_facet: list[str] | None
    person_key: list[str] | None
    time: list[str] | None
    time_facet: list[str] | None
    time_key: list[str] | None
    text: list[str] | None
    seed: list[str] | None
    name: str | None
    name_str: str | None
    alternate_names: list[str] | None
    birth_date: str | None
    death_date: str | None
    date: str | None
    work_count: int | None
    top_work: str | None
    top_subjects: list[str] | None
    subject_type: str | None
