#
# bash startup script to setup environment for OL
#

gitroot=$(git rev-parse --show-toplevel)
pyenv=$(grep '^virtualenv' $gitroot/conf/install.ini | sed -e 's/.*= *//' ) 
pyenv=$(eval echo $pyenv) # expand ~ in the pyenv

export PATH=$gitroot/usr/bin:$PATH
source $pyenv/bin/activate
