FROM ubuntu:xenial

RUN apt-get -qq update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y solr-tomcat && \
    ln -s /var/log/tomcat7/ /usr/share/tomcat7/logs && \
    ln -s /etc/tomcat7/ /usr/share/tomcat7/conf

ARG CONFIG_FILE=solrconfig-dev.xml
COPY conf/solr/conf/* /etc/solr/conf/
RUN ln -sf /etc/solr/conf/$CONFIG_FILE /etc/solr/conf/solrconfig.xml

EXPOSE 8080
CMD ["/usr/share/tomcat7/bin/catalina.sh", "run"]
