FROM ubuntu:xenial

RUN apt-get -qq update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends solr-tomcat haproxy cron && \
    ln -s /var/log/tomcat7/ /usr/share/tomcat7/logs && \
    ln -s /etc/tomcat7/ /usr/share/tomcat7/conf

COPY conf/solr/conf/* /etc/solr/conf/
COPY conf/solr/haproxy.cfg /etc/haproxy/
COPY conf/solr/start.sh /start.sh

# Log management:
COPY conf/solr/rmlog.sh /etc/cron.daily/rmlog
RUN crontab /etc/crontab

EXPOSE 8983
CMD /start.sh
