/**
 * English defaults for every string the librarian workbench renders.
 * The translated set is emitted by templates/librarians/workbench_i18n.html
 * into <ol-workbench data-i18n>; keys here and there must match.
 */
export const DEFAULT_LABELS = {
    // Chrome
    workbench: 'Librarian workbench',
    records: 'Records',
    batches: 'Batches',
    queue: 'Merge queue',
    help: 'Help',
    editions: 'Editions',
    works: 'Works',
    authors: 'Authors',
    search: 'Search',
    searchPlaceholder: 'Free text, or Solr syntax such as author_key:OL26320A',
    run: 'Run',
    worklists: 'Worklists',
    mine: 'Mine',
    builtin: 'Built in',
    saveWorklist: 'Save as worklist',
    worklistName: 'Worklist name',
    rename: 'Rename',
    delete: 'Delete',
    deleteWorklistConfirm: 'Delete this worklist for everyone?',
    filters: 'Filters',
    addFilter: 'Add filter',
    clearFilters: 'Clear filters',
    filterValue: 'Value',
    from: 'From',
    to: 'To',
    sort: 'Sort',
    results: { one: '%(count)s result', other: '%(count)s results' },
    showing: 'Showing %(from)s–%(to)s',
    onPage: 'on this page',
    pageFilterNote: 'Filters marked “on this page” apply to the rows fetched, not the whole index.',
    prev: 'Previous',
    next: 'Next',
    pasteOlids: 'Paste OLIDs',
    pasteHint: 'OLIDs or URLs, one per line or comma-separated',
    load: 'Load',
    noResults: 'No records match.',
    loading: 'Loading…',
    error: 'That didn’t work: %(error)s',
    // Selection
    selected: { one: '%(count)s selected', other: '%(count)s selected' },
    selectPage: 'Select page',
    clear: 'Clear',
    openAll: 'Open all',
    keysHint: 'j/k move · x select · shift+x range · a page · Enter open',
    tooMany: 'A batch takes at most %(max)s records.',
    // Actions
    setAuthor: 'Set author…',
    moveEditions: 'Move editions…',
    manageSubjects: 'Manage subjects…',
    setField: 'Set a field…',
    mergeEditions: 'Merge editions…',
    mergeWorks: 'Merge works…',
    mergeAuthors: 'Merge authors…',
    addToList: 'Add to list…',
    flag: 'Flag for review…',
    deleteRecords: 'Delete…',
    needsTwo: 'Needs at least two',
    superOnly: 'Super-librarians only',
    needsEditions: 'Needs editions',
    needsWorks: 'Needs works',
    needsAuthors: 'Needs authors',
    // Panel
    findings: 'Findings',
    fields: 'Fields',
    belongsTo: 'Belongs to',
    work: 'Work',
    openRecord: 'Open',
    editForm: 'Edit form',
    history: 'History',
    addToSelection: 'Select',
    inSelection: 'Selected',
    pendingChanges: { one: '%(count)s pending change', other: '%(count)s pending changes' },
    pendingNote: 'Nothing is written until you preview and apply.',
    discard: 'Discard',
    previewChanges: 'Preview changes',
    moveToWork: 'Move to another work…',
    moveToNewWork: 'Move to a new work',
    useWorkAuthor: 'Use the work’s author',
    mergeTheseAuthors: 'Merge the two authors…',
    nextRecord: 'Next record',
    prevRecord: 'Previous record',
    close: 'Close',
    notFound: 'Record not found.',
    fieldsNote: 'Title and author links are edited through their own actions, not here.',
    revision: 'revision %(n)s',
    // Preview dialog
    preview: 'Preview',
    apply: 'Apply',
    request: 'Request',
    requested: 'Requested for review',
    reviewNote: 'A super-librarian will review this before it is applied.',
    applied: 'Applied',
    undo: 'Undo',
    undone: 'Reverted',
    cancel: 'Cancel',
    comment: 'Reason (goes in the edit history)',
    changes: 'Changes',
    record: 'Record',
    field: 'Field',
    warnings: 'Warnings',
    survives: 'Survives',
    editionCount: { one: '%(count)s edition', other: '%(count)s editions' },
    workCount: { one: '%(count)s work', other: '%(count)s works' },
    moreRecords: '+%(count)s more',
    more: '… %(count)s more',
    block: 'Blocked',
    warn: 'Check',
    info: 'Note',
    override: 'I’ve checked this',
    noChanges: 'Nothing would change.',
    working: 'Working…',
    failed: 'That didn’t work: %(error)s',
    conflict: 'Some records changed since the preview. Reload and try again.',
    solrLag: 'Applied. Search may take a few minutes to catch up.',
    open: 'Open',
    // Forms
    author: 'Author',
    authorPlaceholder: 'Author name, OLID or URL',
    replaceWith: 'Replace %(name)s with',
    currentAuthors: 'Current authors',
    modeAdd: 'Add',
    modeReplace: 'Replace',
    modeSet: 'Set as the only author',
    includeEditions: 'Also update the editions’ authors',
    targetWork: 'Move to',
    workPlaceholder: 'Work title, OLID or URL',
    newWork: 'A new work',
    newWorkTitle: 'Title for the new work (defaults to the first edition’s)',
    subjectsAdd: 'Add',
    subjectsRemove: 'Remove',
    subjects: 'Subjects',
    subjectPeople: 'People',
    subjectPlaces: 'Places',
    subjectTimes: 'Times',
    commaSeparated: 'Comma-separated',
    fieldName: 'Field',
    fieldValue: 'Value',
    modeSetValue: 'Set',
    modeAppend: 'Append',
    master: 'Surviving edition',
    lowestOlid: 'Lowest OLID',
    reason: 'Reason',
    spam: 'Spam',
    nonBook: 'Not a book',
    duplicate: 'Duplicate',
    toDelete: 'Should be deleted',
    review: 'Needs review',
    includeEditionsDelete: 'Also delete the works’ editions',
    list: 'List',
    chooseList: 'Choose a list',
    added: 'Added %(count)s to the list.',
    // Grid columns
    col_title: 'Title',
    col_author: 'Author',
    col_work: 'Work',
    col_publisher: 'Publisher',
    col_year: 'Year',
    col_isbn: 'ISBN',
    col_language: 'Lang',
    col_scan: 'Scan',
    col_health: 'Health',
    col_source: 'Source',
    col_editions: 'Editions',
    col_subjects: 'Subjects',
    col_readers: 'Readers',
    col_modified: 'Modified',
    col_name: 'Name',
    col_dates: 'Dates',
    col_works: 'Works',
    col_topWork: 'Top work',
    col_ids: 'IDs',
    // Batches tab
    recentBatches: 'Recent batches',
    allBatches: 'All',
    myBatches: 'Mine',
    status: 'Status',
    by: 'by %(username)s',
    applyBatch: 'Apply',
    decline: 'Decline',
    revert: 'Revert',
    forceRevert: 'Revert anyway',
    revertMoved: 'Some records were edited after this batch.',
    viewBatch: 'View',
    noBatches: 'No batches yet.',
};

/** Read the server's translations off a host element's data-i18n, falling back to English. */
export function labelsFromElement(el) {
    try {
        const raw = el?.dataset?.i18n;
        if (raw) return { ...DEFAULT_LABELS, ...JSON.parse(raw) };
    } catch { /* fall through */ }
    return DEFAULT_LABELS;
}
