FROM openlibrary/olbase:latest

ENV PYTHONPATH=/openlibrary:/openlibrary/vendor/infogami
ENV PYENV_VERSION=3.10.0

USER root
COPY requirements*.txt ./
RUN pip install -r requirements_test.txt

WORKDIR /openlibrary/scripts/solr_builder

RUN pip install \
    # For real-time profiling
    cprofilev \
    # Faster python
    Cython

# Build cython files
RUN ./build-cython.sh

EXPOSE 4000
