/**
 * Build the icon assets from static/icons/src/<group>/ (24x24, currentColor
 * SVGs; groups are attribution folders, all read identically). Two outputs,
 * both generated by `make icons` and neither committed:
 *   1. static/icons/sprite.svg — <symbol> sheet for <use> from the document/light
 *      DOM, served as a static asset.
 *   2. openlibrary/components/lit/icons.generated.js — inline Lit templates for
 *      <ol-icon>, which can't reach the sprite from inside a shadow root.
 *      `make lit-components` builds it before bundling.
 *
 * No dependencies, only Node built-ins, so `make icons` runs anywhere without an
 * npm install.
 *
 * Usage: node scripts/build_icon_sprite.mjs
 */
import { readFileSync, readdirSync, renameSync, writeFileSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC_DIR = join(ROOT, "static", "icons", "src");
// Source groups are discovered, not hardcoded, so a new library's folder needs
// no edit here. Sorted so the duplicate-name check fails deterministically.
const SRC_GROUPS = readdirSync(SRC_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
const SPRITE_PATH = join(ROOT, "static", "icons", "sprite.svg");
const JS_MODULE_PATH = join(ROOT, "openlibrary", "components", "lit", "icons.generated.js");

// Namespaces the symbol ids, which are document-wide URL fragments. Callers pass
// bare names; the macro and <ol-icon> add the prefix.
const ID_PREFIX = "icon-";

// A name becomes a JS identifier too, so "3d-view.svg" would emit
// `export const 3dView` and break the build from a generated file.
const NAME_RE = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/;

// Carried from the source <svg> onto the <symbol>; everything else is dropped so
// sizing, stroke weight and a11y are decided at the point of use. stroke-width in
// particular: on the symbol it would outrank the inherited value and CSS can't
// select into a <use> shadow tree, so it must come from the referencing <svg>
// (the --icon-stroke-* tokens in static/css/components/ol-icon.css).
const KEEP_ATTRS = new Set([
    "viewBox",
    "fill",
    "stroke",
    "stroke-linecap",
    "stroke-linejoin",
    "stroke-miterlimit",
    "fill-rule",
    "clip-rule",
]);

/**
 * Attributes of an SVG open tag, as a plain object. Values are read from the
 * double-quoted form only, which is what the optimized sources use.
 *
 * @param {string} openTag - The inside of a `<svg …>` tag, without the brackets.
 * @returns {Record<string, string>} Attribute name -> value, in source order.
 */
function parseAttrs(openTag) {
    const attrs = {};
    for (const m of openTag.matchAll(/([\w:-]+)\s*=\s*"([^"]*)"/g)) {
        attrs[m[1]] = m[2];
    }
    return attrs;
}

/**
 * kebab-case icon name -> camelCase JS identifier (arrow-left -> arrowLeft).
 *
 * @param {string} name - Icon name, already validated against NAME_RE.
 * @returns {string} The JS identifier for that icon's export.
 */
function camelCase(name) {
    return name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

/**
 * Pull the optimized <svg> apart into its root attributes and inner markup.
 *
 * @param {string} svg - Full contents of a source .svg file.
 * @param {string} name - Icon name, used in error messages.
 * @returns {{attrs: Record<string, string>, inner: string}} Root attributes and
 *   the markup between the open and close tags.
 * @throws {Error} If there is no <svg> root or it has no viewBox.
 */
function parseSvg(svg, name) {
    const open = svg.match(/<svg\b([^>]*)>/);
    if (!open) throw new Error(`No <svg> root in ${name}`);
    const inner = svg.slice(open.index + open[0].length, svg.lastIndexOf("</svg>")).trim();
    const attrs = parseAttrs(open[1]);
    if (!attrs.viewBox) throw new Error(`${name} is missing a viewBox`);
    return { attrs, inner };
}

/**
 * The kept root attributes, in source order, as an attribute string.
 *
 * @param {Record<string, string>} attrs - Parsed root attributes.
 * @returns {string} Space-separated `name="value"` pairs for KEEP_ATTRS only.
 */
function keptAttrs(attrs) {
    return Object.entries(attrs)
        .filter(([key]) => KEEP_ATTRS.has(key))
        .map(([key, value]) => `${key}="${value}"`)
        .join(" ");
}

/**
 * The <symbol> the sprite sheet references by id.
 *
 * @param {string} name - Icon name; ID_PREFIX is prepended to form the id.
 * @param {Record<string, string>} attrs - Parsed root attributes.
 * @param {string} inner - The source <svg>'s inner markup.
 * @returns {string} A single-line <symbol> element.
 */
function toSymbol(name, attrs, inner) {
    return `<symbol id="${ID_PREFIX}${name}" ${keptAttrs(attrs)}>${inner}</symbol>`;
}

/**
 * The standalone <svg> <ol-icon> inlines. Same attrs as the symbol, no id.
 *
 * @param {Record<string, string>} attrs - Parsed root attributes.
 * @param {string} inner - The source <svg>'s inner markup.
 * @returns {string} A single-line <svg> element.
 */
function toSvg(attrs, inner) {
    return `<svg ${keptAttrs(attrs)}>${inner}</svg>`;
}

/**
 * Read every source group and build both renderings of each icon. Names must be
 * unique across groups and must not collide once camelCased, since both outputs
 * key on them — the sprite by id, the module by export name.
 *
 * @returns {Map<string, {symbol: string, svg: string}>} Icon name -> its
 *   <symbol> (sprite) and standalone <svg> (Lit module) markup.
 * @throws {Error} On an invalid name, a duplicate name, or an identifier clash.
 */
function collectIcons() {
    const icons = new Map();
    // camelCase identifier -> the name that claimed it. Distinct names can still
    // collide ("heading-1" / "heading1"), emitting the same `export const` twice.
    const identifiers = new Map();
    for (const group of SRC_GROUPS) {
        const dir = join(SRC_DIR, group);
        for (const file of readdirSync(dir)) {
            if (!file.endsWith(".svg")) continue;
            const name = basename(file, ".svg");
            if (!NAME_RE.test(name)) {
                throw new Error(`Invalid icon name "${name}" in ${group}/${file} — use kebab-case starting with a letter, e.g. arrow-left.`);
            }
            if (icons.has(name)) {
                throw new Error(`Duplicate icon name "${name}" (found again in ${group}/)`);
            }
            const identifier = camelCase(name);
            if (identifiers.has(identifier)) {
                throw new Error(
                    `Icon names "${identifiers.get(identifier)}" and "${name}" both map to the JS identifier "${identifier}" in icons.generated.js — rename one.`,
                );
            }
            identifiers.set(identifier, name);
            const raw = readFileSync(join(dir, file), "utf8");
            // Sources are id-free. An id-bearing glyph (gradient, clip-path)
            // would need its inner ids prefixed here, like ID_PREFIX does.
            const { attrs, inner } = parseSvg(raw, name);
            icons.set(name, { symbol: toSymbol(name, attrs, inner), svg: toSvg(attrs, inner) });
        }
    }
    return icons;
}

const icons = collectIcons();
const names = [...icons.keys()].sort();

// 1. Sprite sheet, served as a static asset. Written via a temp file and renamed:
// a rebuild happens under a running server, and a half-written sprite would be
// served as a broken one. One <symbol> per line, so it stays readable.
const symbols = names.map((n) => icons.get(n).symbol).join("\n");
const sprite =
    `<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" style="position:absolute;width:0;height:0;overflow:hidden">` +
    `<defs>\n${symbols}\n</defs></svg>\n`;
writeFileSync(`${SPRITE_PATH}.tmp`, sprite, "utf8");
renameSync(`${SPRITE_PATH}.tmp`, SPRITE_PATH);

// 2. Lit glyph module, the source <ol-icon> renders from. Each export is a
// complete <svg>, so nothing downstream has to know the wrapper's attributes.
// The IIFE puts the PURE annotation before a call expression — the only position
// Rolldown (and terser) honor, so a named import tree-shakes the rest out. The
// `glyphs` map is what <ol-icon> imports, and it necessarily retains all of them.
const jsExports = names
    .map((n) => `export const ${camelCase(n)} = /*#__PURE__*/ (() => html\`${icons.get(n).svg}\`)();`)
    .join("\n");
const jsMap = names.map((n) => `    '${n}': ${camelCase(n)},`).join("\n");
const jsModule =
    "/* eslint-disable */\n" +
    "// @generated by scripts/build_icon_sprite.mjs from static/icons/src/ — DO NOT EDIT.\n" +
    "// Inline icons for Lit components. Prefer <ol-icon name=\"…\">; import a named\n" +
    "// export only when you need the bare <svg> template.\n" +
    "import { html } from 'lit';\n\n" +
    `${jsExports}\n\n` +
    "/** Icon name -> template, for <ol-icon>'s runtime lookup. */\n" +
    `export const glyphs = {\n${jsMap}\n};\n`;
writeFileSync(JS_MODULE_PATH, jsModule, "utf8");

console.log(`Built ${names.length} icons:`);
console.log(`  sprite → ${SPRITE_PATH}`);
console.log(`  module → ${JS_MODULE_PATH}`);
