#! /usr/bin/env python
"""Run coverstore server.

Usage:
    ./scripts/coverstore-server coverstore.yml 8080
    ./scripts/coverstore-server coverstore.yml fastcgi 7070
"""

import sys
import os
import yaml
import web

import _init_path

from openlibrary.coverstore import config, disk, code

_disks = {
    'local': disk.Disk,
    'warc': disk.WARCDisk,
    'archive': disk.ArchiveDisk
}

def make_disk(type, **kw):
    return _disks[type](**kw)

def load_config(configfile):
    d = yaml.load(open(configfile))

    for k, v in d.items():
        setattr(config, k, v)

    config.disk = disk.LayeredDisk([make_disk(**kw) for kw in d['disks']])

def main(configfile, *args):
    load_config(configfile)
    sys.argv = [sys.argv[0]] + list(args)
    code.run()

def archive(configfile):
    from coverstore import archive
    load_config(configfile)
    disks = config.disk.disks
    archive.archive(disks[0], disks[1])

def setup_env():
    # make sure PYTHON_EGG_CACHE is writable
    os.environ['PYTHON_EGG_CACHE'] = "/tmp/.python-eggs"

    # required when run as fastcgi
    os.environ['REAL_SCRIPT_NAME'] = ""
    
if __name__ == "__main__":
    if "--archive" in sys.argv:
        sys.argv.remove('--archive')
        archive(sys.argv[1])
    else:
        setup_env()
        main(*sys.argv[1:])
