#! /usr/bin/env python
"""Script to run infobase.

USAGE:

* Run Infobase http server at port 7070.

    $ python ./scripts/infobase-server infobase.yaml 7070

* Run Infobase as fastcgi server at port 7070

    $ python ./scripts/infobase-server infobase.yaml fastcgi 7070
"""
import sys
import os
import _init_path
import web

from infogami.infobase import server

def setup_env():
    # make sure PYTHON_EGG_CACHE is writable
    os.environ['PYTHON_EGG_CACHE'] = "/tmp/.python-eggs"

    # required when run as fastcgi
    os.environ['REAL_SCRIPT_NAME'] = ""

def main(args):
    if len(args) < 1 or args[0] in ['-h', '--help']:
        print >> sys.stderr, "USAGE: %s configfile [port]" % (sys.argv[0])
        sys.exit(1)
        
    setup_env()
    server.start(*args)

if __name__ == "__main__":
    main(sys.argv[1:])
