#! /usr/bin/env python
"""Script to run openlibrary server.

USAGE:

* Run openlibrary http server at port 8080.

    $ ./scripts/server infogami.yml startserver 8080

* Run openlibrary as fastcgi server at port 7070

    $ ./scripts/server infogami.yml startserver fastcgi 8080
"""
import sys
import _init_path

import infogami
from infogami import config

def main(args):
    if len(args) < 1 or sys.argv[0] in ['-h', '--help']:
        print >> sys.stderr, "USAGE: %s configfile [subcommand] [arguments]" % (sys.argv[0])
        sys.exit(1)
        
    config.plugin_path += ['openlibrary.plugins']
    config.site = "openlibrary.org"
    
    infogami.main(*args)

if __name__ == "__main__":
    main(sys.argv[1:])
