#!/bin/bash

# This file creates a python file that contains the current git commit
# hash and a few other bits of information that can be accessed by the
# app when it starts up. 
#
# This is run just after the checkout is done as part of the
# deployment process and is triggered from the top level Makefile.

INFO_FILE=openlibrary/version.py
githash=$(git log --pretty=%H -1)

echo "# Autogenerated by deployment script at
# $(date)

version = '${githash}'

" > ${INFO_FILE}
