"""Genre → subgenre data behind the home page's "Browse the stacks" section (#13158).

`home_genres.json` is generated by scripts/generate_home_genres.py from the canonical tags
vocabulary. Works aren't tagged with it yet, so each node carries a `subject_key` clause that
approximates the genre against the legacy subject facet.
"""

import functools
import json
from pathlib import Path
from typing import TypedDict, cast

GENRES_JSON_PATH = Path(__file__).parent / "home_genres.json"

# Subgenres with fewer readable books than this (counted at generation time, against
# production) are left off the chip row, so a shelf never opens onto a handful of titles.
MIN_SUBGENRE_READABLE = 100


class GenreNode(TypedDict):
    name: str
    slug: str
    tag_key: str | None
    query: str
    work_count: int
    readable_count: int


class Genre(GenreNode):
    subgenres: list[GenreNode]


@functools.cache
def load_home_genres() -> list[Genre]:
    data = json.loads(GENRES_JSON_PATH.read_text())
    return [
        cast(
            Genre,
            {
                **genre,
                "subgenres": [s for s in genre["subgenres"] if s["readable_count"] >= MIN_SUBGENRE_READABLE],
            },
        )
        for genre in data["genres"]
    ]


def find_genre(slug: str) -> Genre | None:
    return next((g for g in load_home_genres() if g["slug"] == slug), None)


def find_subgenre(genre: Genre, slug: str) -> GenreNode | None:
    return next((s for s in genre["subgenres"] if s["slug"] == slug), None)


def solr_query(node: GenreNode) -> str:
    return f"subject_key:{node['query']}"


def user_language_clause(lang: str | None) -> str:
    """The same language restriction QueryCarousel.html applies for `user_lang_only`."""
    # Imported here: upstream.utils pulls in the plugin package, which would be circular at import time.
    from openlibrary.plugins.upstream.utils import convert_iso_to_marc, get_populated_languages

    marc = convert_iso_to_marc(lang or "en")
    return f" language:{marc}" if marc and marc in get_populated_languages() else ""


def search_url(node: GenreNode, has_fulltext: bool = True) -> str:
    from openlibrary.plugins.upstream.utils import urlencode

    params = {"q": solr_query(node), "sort": "trending"}
    if has_fulltext:
        params["has_fulltext"] = "true"
    return "/search?" + urlencode(params)
