"""Genre → subgenre data behind the home page's "Browse the stacks" section (#13158).

`home_genres.json` is generated by scripts/generate_home_genres.py from the canonical tags
vocabulary. Works aren't tagged with it yet, so each node carries a `subject_key` clause that
approximates the genre against the legacy subject facet.
"""

import functools
import json
from pathlib import Path
from typing import NotRequired, TypedDict, cast

GENRES_JSON_PATH = Path(__file__).parent / "home_genres.json"
# Hand-picked covers for the tiles' fans (see the file's _comment). Not generated.
GENRE_COVERS_JSON_PATH = Path(__file__).parent / "home_genre_covers.json"

# Genres and subgenres with fewer readable books than these (counted at generation time,
# against production) are left off: a tile needs a shelf worth browsing, a subgenre chip needs
# about a carousel's worth. A subgenre's count is for books in both it and its parent.
MIN_GENRE_READABLE = 1000
MIN_SUBGENRE_READABLE = 20
# The shelf picks a subgenre with a segmented control; with "All" that keeps it at four options.
MAX_SUBGENRES = 3

# "Readable" as the carousels' has_fulltext filter means it for most patrons: borrowable or public.
# The raw `has_fulltext` field also counts print-disabled-only books, which most patrons can't open.
READABLE_CLAUSE = "ebook_access:[borrowable TO *]"


class GenreNode(TypedDict):
    name: str
    slug: str
    query: str
    work_count: int
    readable_count: int


class Genre(GenreNode):
    kind: str  # "genre" from the vocabulary, or "subject" for the nonfiction/kids tiles
    page: NotRequired[str]  # subject page to browse, when there is one
    subgenres: list[GenreNode]


@functools.cache
def load_home_genres() -> list[Genre]:
    """Genres first, then the subject tiles; slugs are unique across both."""
    data = json.loads(GENRES_JSON_PATH.read_text())
    return [
        cast(
            Genre,
            {
                **node,
                "kind": kind,
                # The generator sorts subgenres largest first, so the cap keeps the biggest.
                "subgenres": [s for s in node["subgenres"] if s["readable_count"] >= MIN_SUBGENRE_READABLE][:MAX_SUBGENRES],
            },
        )
        for kind, nodes in (("genre", data["genres"]), ("subject", data["subjects"]))
        for node in nodes
        if node["readable_count"] >= MIN_GENRE_READABLE
    ]


@functools.cache
def load_tile_covers() -> dict[str, list[int]]:
    """Cover ids to fan on each tile, keyed by slug. Tiles without an entry use trending covers."""
    data = json.loads(GENRE_COVERS_JSON_PATH.read_text())
    return {slug: [book["cover_id"] for book in books] for slug, books in data["covers"].items()}


def find_genre(slug: str) -> Genre | None:
    return next((g for g in load_home_genres() if g["slug"] == slug), None)


def find_subgenre(genre: Genre, slug: str | None) -> GenreNode | None:
    return next((s for s in genre["subgenres"] if s["slug"] == slug), None)


def solr_query(node: GenreNode, parent: GenreNode | None = None) -> str:
    """A subgenre is searched within its parent: Psychological under Horror is psychological horror."""
    query = f"subject_key:{node['query']}"
    return f"subject_key:{parent['query']} AND {query}" if parent else query


def user_language_clause(lang: str | None) -> str:
    """The same language restriction QueryCarousel.html applies for `user_lang_only`."""
    # Imported here: upstream.utils pulls in the plugin package, which would be circular at import time.
    from openlibrary.plugins.upstream.utils import convert_iso_to_marc, get_populated_languages

    marc = convert_iso_to_marc(lang or "en")
    return f" language:{marc}" if marc and marc in get_populated_languages() else ""


def search_url(node: GenreNode, has_fulltext: bool = True, parent: GenreNode | None = None) -> str:
    from openlibrary.plugins.upstream.utils import urlencode

    params = {"q": solr_query(node, parent), "sort": "trending"}
    if has_fulltext:
        params["has_fulltext"] = "true"
    return "/search?" + urlencode(params)


def browse_url(node: Genre) -> str:
    """Where "Browse all …" goes: the subject page when there is one, else a search."""
    return node.get("page") or search_url(node)
