"""Genre → subgenre data behind the home page's "Browse the stacks" section (#13158).

`home_genres.json` is generated by scripts/generate_home_genres.py from the canonical tags
vocabulary. Works aren't tagged with it yet, so each node carries a `subject_key` clause that
approximates the genre against the legacy subject facet.
"""

import functools
import json
from pathlib import Path
from typing import NotRequired, TypedDict, cast

GENRES_JSON_PATH = Path(__file__).parent / "home_genres.json"

# Genres and subgenres with fewer readable books than these (counted at generation time,
# against production) are left off: a tile needs a shelf worth browsing, a row needs more than
# a handful of titles.
MIN_GENRE_READABLE = 1000
MIN_SUBGENRE_READABLE = 100


class GenreNode(TypedDict):
    name: str
    slug: str
    query: str
    work_count: int
    readable_count: int


class Genre(GenreNode):
    kind: str  # "genre" from the vocabulary, or "subject" for the nonfiction/kids tiles
    page: NotRequired[str]  # subject page to browse, when there is one
    subgenres: list[GenreNode]


@functools.cache
def load_home_genres() -> list[Genre]:
    """Genres first, then the subject tiles; slugs are unique across both."""
    data = json.loads(GENRES_JSON_PATH.read_text())
    return [
        cast(
            Genre,
            {
                **node,
                "kind": kind,
                "subgenres": [s for s in node["subgenres"] if s["readable_count"] >= MIN_SUBGENRE_READABLE],
            },
        )
        for kind, nodes in (("genre", data["genres"]), ("subject", data["subjects"]))
        for node in nodes
        if node["readable_count"] >= MIN_GENRE_READABLE
    ]


def find_genre(slug: str) -> Genre | None:
    return next((g for g in load_home_genres() if g["slug"] == slug), None)


def solr_query(node: GenreNode) -> str:
    return f"subject_key:{node['query']}"


def user_language_clause(lang: str | None) -> str:
    """The same language restriction QueryCarousel.html applies for `user_lang_only`."""
    # Imported here: upstream.utils pulls in the plugin package, which would be circular at import time.
    from openlibrary.plugins.upstream.utils import convert_iso_to_marc, get_populated_languages

    marc = convert_iso_to_marc(lang or "en")
    return f" language:{marc}" if marc and marc in get_populated_languages() else ""


def search_url(node: GenreNode, has_fulltext: bool = True) -> str:
    from openlibrary.plugins.upstream.utils import urlencode

    params = {"q": solr_query(node), "sort": "trending"}
    if has_fulltext:
        params["has_fulltext"] = "true"
    return "/search?" + urlencode(params)


def browse_url(node: Genre) -> str:
    """Where "Browse all …" goes: the subject page when there is one, else a search."""
    return node.get("page") or search_url(node)
