name: pr_changes_requested_labeler
on:
  pull_request_review:
    types:
      - submitted
env:
  NODE_VERSION: '24'
jobs:
  label_pr:
    if: ${{ github.repository == github.event.repository.full_name && github.event.review.state == 'changes_requested' }}
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v5
        id: cache-octokit
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node${{ env.NODE_VERSION }}-octokit-${{ hashFiles('**/package-lock.json') }}
      - if: steps.cache-octokit.outputs.cache-hit != 'true'
        run: npm install @octokit/action
      - run: node scripts/gh_scripts/pr_changes_requested_labeler.mjs ${{ github.repository }} ${{ github.event.pull_request.number }} ${{ github.event.review.state }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
