name: weekly_status_report
on:
  schedule:
    - cron: '30 8 * * 1,5'
  workflow_dispatch:
permissions:
  contents: read
  issues: read
env:
  NODE_VERSION: '24'
  TEAM_ABC_CONFIG: '.github/workflows/config/weekly_status_report_team_abc.json'
  LEADS_G_CONFIG: '.github/workflows/config/weekly_status_report_openlibrary_leads_g.json'
jobs:
  create_and_publish_report:
    if: github.repository_owner == 'internetarchive'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        id: cache-octokit
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node${{ env.NODE_VERSION}}-octokit-${{ hashFiles('**/package-lock.json') }}
      - if: steps.cache-octokit.outputs.cache-hit != 'true'
        run: npm install @octokit/action  # zizmor: ignore[adhoc-packages]
      - run: node scripts/gh_scripts/weekly_status_report.mjs ${{ env.TEAM_ABC_CONFIG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      - run: node scripts/gh_scripts/weekly_status_report.mjs ${{ env.LEADS_G_CONFIG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
