#!/usr/bin/python
import unittest

from parse import read_edition, SeeAlsoAsTitle, NoTitle
from marc_binary import MarcBinary
from marc_xml import MarcXml, BadSubtag, BlankTag
from pprint import pprint, pformat
from urllib import urlopen
from lxml import etree

record_tag = '{http://www.loc.gov/MARC21/slim}record'

xml_samples = [
('39002054008678.yale.edu', {'publishers': [u'W. Briggs'], 'pagination': u'243 p., [27] leaves of plates :', 'number_of_pages': 243,
    'title': u'Upper Canada sketches', 'lccn': [u'02012591'],
    'authors': [{'birth_date': u'1842', 'personal_name': u'Conant, Thomas', 'death_date': u'1905', 'name': u'Conant, Thomas', 'entity_type': 'person'}], 
    'languages': [{'key': '/languages/eng'}], 'publish_date': '1898', 'publish_country': 'onc', 'lc_classification': [u'F1058 .C74'],
    'by_statement': u'by Thomas Conant', 'publish_places': [u'Toronto'], 'oclc_number': [u'9268563']} ),
('flatlandromanceo00abbouoft', {'publishers': [u'Seeley and Co.'], 'pagination': u'viii p., 1 l.,', 'subtitle': u'a romance of many dimensions',
    'title': u'Flatland', 'notes': u'31', 'lc_classification': [u'QA699 .A12'], 'languages': [{'key': '/languages/eng'}], 'publish_date': '1884', 'publish_country': 'enk',
    'authors': [{'birth_date': u'1838', 'personal_name': u'Abbott, Edwin Abbott', 'death_date': u'1926', 'name': u'Abbott, Edwin Abbott', 'entity_type': 'person'}],
    'by_statement': u'by A. Square ; with illustrations by the author', 'publish_places': [u'London']} ),
('nybc200247', {'other_titles': [u'Tzum hundertstn geboirntog fun Shimen Dubnow', u'Centennial of the historian Shimen Dubnow'], 
    'pagination': u'92 p. :',
    'table_of_contents': [{'type': '/type/toc_item', 'title': u'Ar\u1e6di\u1e33len vegn Shimen Dubnov'}, {'type': '/type/toc_item', 'title': u'Ophandlungen un ar\u1e6di\u1e33len fun Shimen Dubnov'}, {'type': '/type/toc_item', 'title': u'Briv fun Sh. Dubnov.'}], 'subtitle': u'zamlung', 'title': u'Tsum hunderts\u1e6dn geboyrn\u1e6dog fun Shimon Dubno\u1e7f',
    'series': [u'Steven Spielberg digital Yiddish library -- no. 00247'], 'notes': u'Electronic reproduction. Amherst : National Yiddish Book Center, 1999.\n\nThis item is offered for sale by the National Yiddish Book Center. Internet: www.yiddishbooks.org; email: orders@bikher.org; phone: 413.256.4900; fax: 413.256.4700', 'number_of_pages': 92, 'languages': [{'key': '/languages/yid'}],
    'publishers': [u'I\u1e33uf'], 'publish_date': '1961', 'publish_country': 'nyu',
    'authors': [{'birth_date': u'1860', 'personal_name': u'Dubnow, Simon', 'death_date': u'1941', 'name': u'Dubnow, Simon', 'entity_type': 'person'}], 'by_statement': u'tsunoyfgesh.tel\u1e6d un reda\u1e33\u1e6dir\u1e6d fun Na\u1e25man Mayzil', 'publish_places': [u'Nyu-Yor\u1e33'], 'contributions': [u'Mayzel, Nachman, 1887-1966.']} ),
('secretcodeofsucc00stjo', {'publishers': [u'HarperCollins Publishers'], 'pagination': u'xi, 243 p.', 'number_of_pages': 243,
    'table_of_contents': [{'type': '/type/toc_item', 'title': u'The secret of success in life and business'}, {'type': '/type/toc_item', 'title': u"What's wrong with this picture?"}, {'type': '/type/toc_item', 'title': u"The little assumption that's costing you a fortune"}, {'type': '/type/toc_item', 'title': u'The secret code revealed'}, {'type': '/type/toc_item', 'title': u'Step one: afformations'}, {'type': '/type/toc_item', 'title': u'Step two: loving mirrors and safe havens'}, {'type': '/type/toc_item', 'title': u'Step three: systems of support'}, {'type': '/type/toc_item', 'title': u'Step four: goal-free zones and goal replacement surgery'}, {'type': '/type/toc_item', 'title': u'Step five : who are you trying to protect, punish or please?'}, {'type': '/type/toc_item', 'title': u'Step six: find your no'}, {'type': '/type/toc_item', 'title': u'Step seven: find your because'}, {'type': '/type/toc_item', 'title': u'Now what?'}, {'type': '/type/toc_item', 'title': u'Your free bonus gift'}, {'type': '/type/toc_item', 'title': u'Spread the word.'}], 'description': u'Americans spend billions on self-help products, yet few people are living the life they really want. The real problem, says productivity expert Noah St. John, is that most people focus on the "how-to" aspects of success without coming to terms with what calls your "head trash"-the subconscious, emotional roadblocks that prevent people from acting on their real hopes, dreams, and ambitions. St. John has created a seven-step approach that helps you learn how to: eliminate the causes of self-sabotage and fear of success; allow yourself to make more money; remove stress while dramatically increasing personal productivity; improve relationships with coworkers, family, and friends; and experience enhanced feelings of happiness, connection, and love.--From publisher description.', 'links': [{'url': u'http://www.loc.gov/catdir/toc/ecip0824/2008033690.html', 'title': u'Table of contents only'}], 'title': u'The secret code of success', 'lccn': [u'2008033690'], 'notes': u'Includes indexes.',
    'authors': [{'birth_date': u'1967', 'personal_name': u'St. John, Noah', 'name': u'St. John, Noah', 'entity_type': 'person'}], 'isbn_13': [u'9780061715747', u'9780061764547'], 'subtitle': u'7 hidden steps to more wealth and happiness', 'languages': [{'key': '/languages/eng'}], 'dewey_decimal_class': [u'650.1'],
    'isbn_10': [u'0061715743', u'006176454X'], 'publish_date': '2009', 'publish_country': 'nyu', 'lc_classification': [u'HF5386 .S7595 2009'], 'by_statement': u'by Noah St. John ; foreword by Jack Canfield', 'publish_places': [u'New York'], 'oclc_number': [u'232977651']} ),
('warofrebellionco1473unit', {'other_titles': [u'Official records of the Union and Confederate Armies.'], 'publishers': [u'Govt. Print. Off.'], 'pagination': u'70 v. in 128 ;',
    'number_of_pages': 128,
    'subtitle': u'a compilation of the official records of the Union and Confederate armies', 'title': u'The War of the Rebellion', 'lccn': [u'03003452'], 'notes': u'Found also in the House Miscellaneous documents of the 52d to the 56th Congress.\n\nEach number has special index. Inserted in each volume: Additions and corrections ... Washington, Govt. Print. Off., 1902.\n\nSeries 1, v. 1-53, series 3, v. 1-5, and series 4, v. 1-3 include "Alternate designations of organizations mentioned."\n\nVol. 54-55 of series 1 [serial no. 112-113] "have not been published, and no material for them is in hand."  cf. General index, p. xi. Series 2, v. 1 [serial no. 114] with imprint 1894, was not issued until 1898.\n\nEdited in the War Records Office, 1880-July 1899; in the Record and Pension Office, July 1899-1901.\n\nRobert N. Scott compiled and edited v. 1-18, 1880-87, and also collected the greater part of the material for v. 19-36, 1887-91. After his death in 1887 the work was continued by Henry M. Lazelle, 1887-89, and by a board of publication, 1889-99, consisting of George B. Davis, 1889-97, Leslie J. Perry, 1889-99, Joseph W. Kirkley, 1889-99, and Fred C. Ainsworth, 1898-99; from 1899-1901 edited by Fred C. Ainsworth and Joesph W. Kirkley.\n\nSome volumes are 1985 reprints by National Historical Society.\n\n16',
    'authors': [{'name': u'United States. War Dept.', 'entity_type': 'org'}], 'languages': [{'key': '/languages/eng'}],
    'publish_date': '1880', 'publish_country': 'dcu', 'lc_classification': [u'E464 .U6'], 'by_statement': u'prepared under the direction of the Secretary of War', 'publish_places': [u'Washington'], 'contributions': [u'Scott, Robert N. 1838-1887.', u'Lazelle, Henry Martyn, 1832-', u'Davis, George B. 1847-1914.', u'Perry, Leslie J.', u'Kirkley, Joseph W. 1841-1912.', u'Ainsworth, Frederick Crayton, 1852-1834.', u'Moodey, John Sheldon, 1842-', u'Cowles, Calvin D. 1849- comp.', u'United States. War Records Office.', u'United States. Record and Pension Office.', u'United States. Congress. House.']} ),
('zweibchersatir01horauoft', {'publishers': [u'Teubner'], 'pagination': u'2 vol. in 3.',
    'table_of_contents': [{'type': '/type/toc_item', 'title': u'Vol. 1. Text, \xdcbersetzung und kritischer Apparat.-  Vol. 2, pt. 1, Commentar zum ersten Buche der Satiren.-  Vol. 2, pt. 2, Commentar zum zweiten Buche der Satiren, verfasst von W.S. Teuffel.'}], 'title': u'Zwei B\xfccher Satiren', 'work_titles': [u'Satirae'], 'notes': u'26', 'languages': [{'key': '/languages/ger'}], 'publish_date': '1854', 'publish_country': 'ge ',
    'authors': [{'personal_name': u'Horace.', 'name': u'Horace.', 'entity_type': 'person'}], 'by_statement': u'aus dreissig unverglichenen und allen bisher verglichenen Handschriften, wie auch s\xe4mmtlichen bedeutenden Ausgaben kritisch hergestellt, metrisch \xfcbersetzt, und mit erkl\xe4rendem Commentar versehen von C. Kirchner', 'publish_places': [u'Leipzig'], 'contributions': [u'Kirchner, Carl Christian Jacob, 1787-1855, tr. [and] ed.', u'Teuffel, Wilhelm Sigmund, 1820-1878,']} ),
]

bin_samples = '''
    bpl_0486266893
    flatlandromanceo00abbouoft_meta.mrc
    histoirereligieu05cr_meta.mrc
    ithaca_college_75002321
    lc_0444897283
    lc_1416500308
    ocm00400866
    secretcodeofsucc00stjo_meta.mrc
    uoft_4351105_1626
    warofrebellionco1473unit_meta.mrc
    wrapped_lines
    wwu_51323556
    zweibchersatir01horauoft_meta.mrc
'''.split()

bin_samples = [
('bpl_0486266893', {'authors': [{'birth_date': u'1694', 'death_date': u'1778', 'entity_type': 'person', 'name': u'Voltaire', 'personal_name': u'Voltaire'}],
 'by_statement': u'Voltaire',
 'dewey_decimal_class': [u'843/.5'],
 'edition_name': [u'Dover Thrift ed.'],
 'isbn_10': [u'0486266893'],
 'languages': [{'key': '/languages/eng'}],
 'lc_classification': [u'PQ2082.C3 E5 1991'],
 'lccn': [u'90020571'],
 'notes': u'Translation from French.',
 'number_of_pages': 94,
 'pagination': u'ix, 94 p. ;',
 'publish_country': 'nyu',
 'publish_date': '1991',
 'publish_places': [u'New York'],
 'publishers': [u'Dover Publications'],
 'series': [u'Dover thrift editions', u'Dover thrift editions'],
 'title': u'Candide',
 'work_titles': [u'Candide.']}),
('flatlandromanceo00abbouoft_meta.mrc', {
    'authors': [{'birth_date': u'1838', 'death_date': u'1926', 'entity_type': 'person', 'name': u'Abbott, Edwin Abbott',
              'personal_name': u'Abbott, Edwin Abbott'}],
 'by_statement': u'by A. Square ; with illustrations by the author',
 'languages': [{'key': '/languages/eng'}],
 'lc_classification': [u'QA699 .A12'],
 'notes': u'31',
 'pagination': u'viii p., 1 l.,',
 'publish_country': 'enk',
 'publish_date': '1884',
 'publish_places': [u'London'],
 'publishers': [u'Seeley and Co.'],
 'subtitle': u'a romance of many dimensions',
 'title': u'Flatland'}),
('histoirereligieu05cr_meta.mrc', {'authors': [{'birth_date': u'1803',
              'death_date': u'1875',
              'entity_type': 'person',
              'name': u'Cr\xe2etineau-Joly, J.',
              'personal_name': u'Cr\xe2etineau-Joly, J.'}],
 'by_statement': u'par J. Cr\xe2etineau-Joly',
 'edition_name': [u'Deuxi\xe1eme ed.'],
 'languages': [{'key': '/languages/fre'}],
 'notes': u'STH Library: has vols. 2-6 only.',
 'oclc_number': ['10603157'],
 'pagination': u'6 v. :',
 'publish_country': 'fr ',
 'publish_date': '1846',
 'publish_places': [u'Paris', u'Lyon'],
 'publishers': [u'Librarie Religieuse Mellier Fr\xe1eres', u'Guyot'],
 'subtitle': u'compos\xe2ee sur les documents in\xe2edidts et authentiques',
 'title': u'Histoire religieuse, politique et litt\xe2eraire de la Compagnie de J\xe2esus'}),
('ithaca_college_75002321', {'by_statement': u'editors, Joseph A. Pechman, P. Michael Timpane',
 'contributions': [u'Pechman, Joseph A., 1918-',
                   u'Timpane, P. Michael, 1934-',
                   u'Brookings Institution, Washington, D.C. Panel on Social Experimentation.'],
 'dewey_decimal_class': [u'361.6/2/09749'],
 'isbn_10': [u'0815769768', u'081576975X'],
 'languages': [{'key': '/languages/eng'}],
 'lc_classification': [u'HC107.N53 I58'],
 'lccn': [u'\u02b9  75002321'],
 'notes': u'Papers and comments presented at the conference at Brookings Institution, Apr. 29-30, 1974, sponsored by the Brookings Panel on Social Experimentation.\n\nIncludes bibliographical references and index.',
 'number_of_pages': 232,
 'pagination': u'xiii, 232 p. ;',
 'publish_country': 'dcu',
 'publish_date': '1975',
 'publish_places': [u'Washington'],
 'publishers': [u'Brookings Institution'],
 'series': [u'Brookings studies in social experimentation'],
 'subtitle': u'the New Jersey negative income tax experiment',
 'title': u'Work incentives and income guarantees'}),
('lc_0444897283', {'authors': [{'entity_type': 'event',
              'name': u'IFIP TC5/WG 5.6 International Conference on Computer Applications in the Automation of Shipyard Operation and Ship Design (7th 1991 Rio de Janeiro, Brazil)'}],
 'by_statement': u'edited by Claudio Bara\xfana Vieira, Prot\xe1sio Martins, Chengi Kuo',
 'contributions': [u'Vieira, Claudio Bara\xfana, 1944-',
                   u'Martins, Prot\xe1sio, 1950-',
                   u'Kuo, Chengi.'],
 'dewey_decimal_class': [u'623.8/1/0285'],
 'isbn_10': [u'0444897283'],
 'languages': [{'key': '/languages/eng'}],
 'lc_classification': [u'VM156 .I35 1991'],
 'lccn': [u'92021617'],
 'notes': u'Includes bibliographical references.',
 'number_of_pages': 376,
 'pagination': u'ix, 376 p. :',
 'publish_country': 'ne ',
 'publish_date': '1992',
 'publish_places': [u'Amsterdam', u'New York'],
 'publishers': [u'North-Holland'],
 'series': [u'IFIP transactions -- B-5'],
 'subtitle': u'proceedings of the IFIP TC5/WG 5.6 Seventh International Conference on Computer Applications in the Automation of Shipyard Operation and Ship Design, VII : Rio de Janeiro, Brazil, 10-13 September 1991',
 'title': u'Computer applications in the automation of shipyard operation and ship design, VII'}),
('lc_1416500308', {'authors': [{'birth_date': u'1694',
              'death_date': u'1778',
              'entity_type': 'person',
              'name': u'Voltaire',
              'personal_name': u'Voltaire'}],
 'by_statement': u'Voltaire ; supplementary material written by Alyssa Harad',
 'isbn_10': [u'1416500308'],
 'languages': [{'key': '/languages/eng'}],
 'lc_classification': [u'PQ2082.C3 E5 2005c'],
 'lccn': [u'2005280851'],
 'number_of_pages': 178,
 'pagination': u'178 p. ;',
 'publish_country': 'nyu',
 'publish_date': '2005',
 'publish_places': [u'New York'],
 'publishers': [u'Pocket Books'],
 'series': [u'Enriched classics', u'Enriched classics series'],
 'title': u'Candide',
 'work_titles': [u'Candide.']}),
('ocm00400866', {'authors': [{'entity_type': 'person',
              'name': u'Armitage, M. Teresa',
              'personal_name': u'Armitage, M. Teresa'}],
 'edition_name': [u"Teachers' edition"],
 'languages': [{'key': '/languages/eng'}],
 'notes': u'For mixed voices 1-4 parts with piano accompaniments',
 'number_of_pages': 572,
 'pagination': u'572 p. ;',
 'publish_date': '1926',
 'publish_places': [u'Boston'],
 'publishers': [u'C. C. Birchard'],
 'series': [u'The Laurel music series'],
 'table_of_contents': [{'title': u'Abide with me', 'type': '/type/toc_item'},
                       {'title': u'Absent-minded serenade',
                        'type': '/type/toc_item'},
                       {'title': u'Ah, leave me not alone',
                        'type': '/type/toc_item'},
                       {'title': u'Alice, where art thou?',
                        'type': '/type/toc_item'},
                       {'title': u'A little sun, a little rain',
                        'type': '/type/toc_item'},
                       {'title': u'Alleluia', 'type': '/type/toc_item'},
                       {'title': u'Allah', 'type': '/type/toc_item'},
                       {'title': u'All is well', 'type': '/type/toc_item'},
                       {'title': u'All through the night',
                        'type': '/type/toc_item'},
                       {'title': u'All ye that weep',
                        'type': '/type/toc_item'},
                       {'title': u'Although our dark career',
                        'type': '/type/toc_item'},
                       {'title': u'America', 'type': '/type/toc_item'},
                       {'title': u'America the beautiful',
                        'type': '/type/toc_item'},
                       {'title': u'The angelus', 'type': '/type/toc_item'},
                       {'title': u'Annie Laurie', 'type': '/type/toc_item'},
                       {'title': u'April wakes', 'type': '/type/toc_item'},
                       {'title': u"Ariel's song", 'type': '/type/toc_item'},
                       {'title': u'A-roving', 'type': '/type/toc_item'},
                       {'title': u'The ash grove', 'type': '/type/toc_item'},
                       {'title': u'At evening', 'type': '/type/toc_item'},
                       {'title': u'At the spinning wheel',
                        'type': '/type/toc_item'},
                       {'title': u'Auld lang syne', 'type': '/type/toc_item'},
                       {'title': u'Autumn scene', 'type': '/type/toc_item'},
                       {'title': u'Ave Maria', 'type': '/type/toc_item'},
                       {'title': u'Baccalaureate hymn',
                        'type': '/type/toc_item'},
                       {'title': u'The bark canoe', 'type': '/type/toc_item'},
                       {'title': u'Battle hymn of the republic',
                        'type': '/type/toc_item'},
                       {'title': u'Behold the Lord High Executioner',
                        'type': '/type/toc_item'},
                       {'title': u'Bells of Aberdovey',
                        'type': '/type/toc_item'},
                       {'title': u'Bleesed are the peacemakers',
                        'type': '/type/toc_item'},
                       {'title': u'The blue flower',
                        'type': '/type/toc_item'},
                       {'title': u'Breakers', 'type': '/type/toc_item'},
                       {'title': u'Break forth, o beauteous heavenly light',
                        'type': '/type/toc_item'},
                       {'title': u'Bring the wagon home, John',
                        'type': '/type/toc_item'},
                       {'title': u'Brotherhood', 'type': '/type/toc_item'},
                       {'title': u'Bunches of grapes',
                        'type': '/type/toc_item'},
                       {'title': u'By peaceful hearth',
                        'type': '/type/toc_item'},
                       {'title': u'The call', 'type': '/type/toc_item'},
                       {'title': u'Calm as the night',
                        'type': '/type/toc_item'},
                       {'title': u'Camp song', 'type': '/type/toc_item'},
                       {'title': u'Canoeing', 'type': '/type/toc_item'},
                       {'title': u'Captain Kidd', 'type': '/type/toc_item'},
                       {'title': u'Carmen Carmela', 'type': '/type/toc_item'},
                       {'title': u'Carmelina', 'type': '/type/toc_item'},
                       {'title': u'Carol of the birds',
                        'type': '/type/toc_item'},
                       {'title': u'The carrier dove',
                        'type': '/type/toc_item'},
                       {'title': u'Carry me back to old Virginny',
                        'type': '/type/toc_item'},
                       {'title': u'The cat and the catboat',
                        'type': '/type/toc_item'},
                       {'title': u"Charlie is my darlin'",
                        'type': '/type/toc_item'},
                       {'title': u'Cheerio', 'type': '/type/toc_item'},
                       {'title': u'Cherry bloom', 'type': '/type/toc_item'},
                       {'title': u'Chinese hymn', 'type': '/type/toc_item'},
                       {'title': u'Choral sanctus', 'type': '/type/toc_item'},
                       {'title': u'Christmas greeting',
                        'type': '/type/toc_item'},
                       {'title': u'Christ the Lord is risen today',
                        'type': '/type/toc_item'},
                       {'title': u'Closing hymn', 'type': '/type/toc_item'},
                       {'title': u'Columbia the gem of the ocean',
                        'type': '/type/toc_item'},
                       {'title': u'Columbus', 'type': '/type/toc_item'},
                       {'title': u'Come, thou almighty King',
                        'type': '/type/toc_item'},
                       {'title': u'Coronation', 'type': '/type/toc_item'},
                       {'title': u'The counter-charm',
                        'type': '/type/toc_item'},
                       {'title': u'Creator alme siderum',
                        'type': '/type/toc_item'},
                       {'title': u'The Danube river',
                        'type': '/type/toc_item'},
                       {'title': u'The dawn of Maytime',
                        'type': '/type/toc_item'},
                       {'title': u'Dayspring', 'type': '/type/toc_item'},
                       {'title': u'Dear one, believe (Caro mio ben)',
                        'type': '/type/toc_item'},
                       {'title': u'Dialgue', 'type': '/type/toc_item'},
                       {'title': u'Dixie', 'type': '/type/toc_item'},
                       {'title': u'Dogie song', 'type': '/type/toc_item'},
                       {'title': u'The dove', 'type': '/type/toc_item'},
                       {'title': u'Down in Dixie', 'type': '/type/toc_item'},
                       {'title': u'Down Mobile', 'type': '/type/toc_item'},
                       {'title': u'Drink to me only wtih thine eyes',
                        'type': '/type/toc_item'},
                       {'title': u'Easter', 'type': '/type/toc_item'},
                       {'title': u'Echo', 'type': '/type/toc_item'},
                       {'title': u'Evening in the tropics',
                        'type': '/type/toc_item'},
                       {'title': u'Evening prayer', 'type': '/type/toc_item'},
                       {'title': u'Evening song', 'type': '/type/toc_item'},
                       {'title': u'Fair glows the earth',
                        'type': '/type/toc_item'},
                       {'title': u'Fairy friends', 'type': '/type/toc_item'},
                       {'title': u'Faith of our fathers',
                        'type': '/type/toc_item'},
                       {'title': u'The first Nowell',
                        'type': '/type/toc_item'},
                       {'title': u'Flag song', 'type': '/type/toc_item'},
                       {'title': u'A flower song', 'type': '/type/toc_item'},
                       {'title': u'Flow gently, sweet Afton',
                        'type': '/type/toc_item'},
                       {'title': u'Forget-me-not', 'type': '/type/toc_item'},
                       {'title': u'The four winds', 'type': '/type/toc_item'},
                       {'title': u'The generous heart',
                        'type': '/type/toc_item'},
                       {'title': u'Gypsy John', 'type': '/type/toc_item'},
                       {'title': u'Gipsy life', 'type': '/type/toc_item'},
                       {'title': u'Gipsy song', 'type': '/type/toc_item'},
                       {'title': u'Gloria', 'type': '/type/toc_item'},
                       {'title': u'Glory now to thee be given',
                        'type': '/type/toc_item'},
                       {'title': u'Glory to him', 'type': '/type/toc_item'},
                       {'title': u'Glorious things of thee are spoken',
                        'type': '/type/toc_item'},
                       {'title': u'God ever glorious',
                        'type': '/type/toc_item'},
                       {'title': u'God of all nature',
                        'type': '/type/toc_item'},
                       {'title': u'God rest you merry, gentlemen',
                        'type': '/type/toc_item'},
                       {'title': u'Go down, Moses', 'type': '/type/toc_item'},
                       {'title': u'Go to it', 'type': '/type/toc_item'},
                       {'title': u'Great God, we sing that mighty hand',
                        'type': '/type/toc_item'},
                       {'title': u'Hail Columbia', 'type': '/type/toc_item'},
                       {'title': u'Happy days', 'type': '/type/toc_item'},
                       {'title': u'The happy family',
                        'type': '/type/toc_item'},
                       {'title': u'Hark hark the lark',
                        'type': '/type/toc_item'},
                       {'title': u'Hear the noisy wind',
                        'type': '/type/toc_item'},
                       {'title': u'Hearld of happiness',
                        'type': '/type/toc_item'},
                       {'title': u"Here's a first rate opportunity",
                        'type': '/type/toc_item'},
                       {'title': u'Hit the line', 'type': '/type/toc_item'},
                       {'title': u'Hold thy peace', 'type': '/type/toc_item'},
                       {'title': u'Home is wating', 'type': '/type/toc_item'},
                       {'title': u'Homeland', 'type': '/type/toc_item'},
                       {'title': u'The honey bee', 'type': '/type/toc_item'},
                       {'title': u'Hope and faith', 'type': '/type/toc_item'},
                       {'title': u'A hope carol', 'type': '/type/toc_item'},
                       {'title': u'Horn music', 'type': '/type/toc_item'},
                       {'title': u'How lovely are the messengers',
                        'type': '/type/toc_item'},
                       {'title': u"I ain't gwine to study war no more",
                        'type': '/type/toc_item'},
                       {'title': u'I am a pirate king',
                        'type': '/type/toc_item'},
                       {'title': u'I am the captain of the Pinafore',
                        'type': '/type/toc_item'},
                       {'title': u'I am the monarch of the sea',
                        'type': '/type/toc_item'},
                       {'title': u'If I could fly', 'type': '/type/toc_item'},
                       {'title': u"I'm called Little Buttercup",
                        'type': '/type/toc_item'},
                       {'title': u'Inconsequence', 'type': '/type/toc_item'},
                       {'title': u'The inglenook', 'type': '/type/toc_item'},
                       {'title': u'In Hawaii', 'type': '/type/toc_item'},
                       {'title': u'In memoriam', 'type': '/type/toc_item'},
                       {'title': u'In old Versailles',
                        'type': '/type/toc_item'},
                       {'title': u'In summer', 'type': '/type/toc_item'},
                       {'title': u'In the forest', 'type': '/type/toc_item'},
                       {'title': u'An Irish love song',
                        'type': '/type/toc_item'},
                       {'title': u"I've no time to be a-sighin'",
                        'type': '/type/toc_item'},
                       {'title': u'Jeanie with the light brown hair',
                        'type': '/type/toc_item'},
                       {'title': u'Jerusalem', 'type': '/type/toc_item'},
                       {'title': u'Jerusalem the golden',
                        'type': '/type/toc_item'},
                       {'title': u'Joy of the hour',
                        'type': '/type/toc_item'},
                       {'title': u'Jubilate', 'type': '/type/toc_item'},
                       {'title': u"Keep a-goin'", 'type': '/type/toc_item'},
                       {'title': u'Keeping on', 'type': '/type/toc_item'},
                       {'title': u'Keep us, O Lord',
                        'type': '/type/toc_item'},
                       {'title': u"Keller's American hymn",
                        'type': '/type/toc_item'},
                       {'title': u'Kimi-ga-yo', 'type': '/type/toc_item'},
                       {'title': u'King of glory', 'type': '/type/toc_item'},
                       {'title': u'King of Yvetot', 'type': '/type/toc_item'},
                       {'title': u'Lady Moon', 'type': '/type/toc_item'},
                       {'title': u'The lake at night',
                        'type': '/type/toc_item'},
                       {'title': u'Land of the midnight sun',
                        'type': '/type/toc_item'},
                       {'title': u'Largo', 'type': '/type/toc_item'},
                       {'title': u'Laughing song', 'type': '/type/toc_item'},
                       {'title': u'Law and order', 'type': '/type/toc_item'},
                       {'title': u'Law is the true embodiment',
                        'type': '/type/toc_item'},
                       {'title': u'Lead kindly light',
                        'type': '/type/toc_item'},
                       {'title': u'Let peace endure',
                        'type': '/type/toc_item'},
                       {'title': u'Let the whole creation cry',
                        'type': '/type/toc_item'},
                       {'title': u'Light', 'type': '/type/toc_item'},
                       {'title': u'Lincoln', 'type': '/type/toc_item'},
                       {'title': u'Lincoln marching song',
                        'type': '/type/toc_item'},
                       {'title': u'Loch Lomond', 'type': '/type/toc_item'},
                       {'title': u'Lo, what a branch of beauty',
                        'type': '/type/toc_item'},
                       {'title': u'Lord of light', 'type': '/type/toc_item'},
                       {'title': u'Lord, with undying love',
                        'type': '/type/toc_item'},
                       {'title': u"Love's greeting (Salut d'amour)",
                        'type': '/type/toc_item'},
                       {'title': u"Love's old sweet song",
                        'type': '/type/toc_item'},
                       {'title': u'Lullaby', 'type': '/type/toc_item'},
                       {'title': u'Lullaby of life',
                        'type': '/type/toc_item'},
                       {'title': u'The lullaby', 'type': '/type/toc_item'},
                       {'title': u'Madeleine', 'type': '/type/toc_item'},
                       {'title': u'Madrigal', 'type': '/type/toc_item'},
                       {'title': u'Magnet and the churn',
                        'type': '/type/toc_item'},
                       {'title': u'The Magyars', 'type': '/type/toc_item'},
                       {'title': u'A maiden fair to see',
                        'type': '/type/toc_item'},
                       {'title': u'the man in the moon',
                        'type': '/type/toc_item'},
                       {'title': u'Marching song', 'type': '/type/toc_item'},
                       {'title': u'March of civilization',
                        'type': '/type/toc_item'},
                       {'title': u'Marianina', 'type': '/type/toc_item'},
                       {'title': u'Mass dear', 'type': '/type/toc_item'},
                       {'title': u'Matin song', 'type': '/type/toc_item'},
                       {'title': u'Matona', 'type': '/type/toc_item'},
                       {'title': u'A May dance', 'type': '/type/toc_item'},
                       {'title': u'May in flower', 'type': '/type/toc_item'},
                       {'title': u'The Mazurka', 'type': '/type/toc_item'},
                       {'title': u'Menuetto pastorale',
                        'type': '/type/toc_item'},
                       {'title': u'Meow', 'type': '/type/toc_item'},
                       {'title': u'The messenger', 'type': '/type/toc_item'},
                       {'title': u'Missionary chant',
                        'type': '/type/toc_item'},
                       {'title': u'The moon', 'type': '/type/toc_item'},
                       {'title': u'Moonlight serenade',
                        'type': '/type/toc_item'},
                       {'title': u'Morn of May', 'type': '/type/toc_item'},
                       {'title': u'Mother Volga', 'type': '/type/toc_item'},
                       {'title': u'The mountain brook',
                        'type': '/type/toc_item'},
                       {'title': u'A mountain picture',
                        'type': '/type/toc_item'},
                       {'title': u'A mountain romance',
                        'type': '/type/toc_item'},
                       {'title': u'Music in China', 'type': '/type/toc_item'},
                       {'title': u'My object all sublime',
                        'type': '/type/toc_item'},
                       {'title': u'My old Kentucky home',
                        'type': '/type/toc_item'},
                       {'title': u'My ship', 'type': '/type/toc_item'},
                       {'title': u'My sunshine', 'type': '/type/toc_item'},
                       {'title': u'Nathan Hale', 'type': '/type/toc_item'},
                       {'title': u'Nazareth', 'type': '/type/toc_item'},
                       {'title': u"'Neath our flag",
                        'type': '/type/toc_item'},
                       {'title': u"'Neath the window",
                        'type': '/type/toc_item'},
                       {'title': u"New Year's Eve", 'type': '/type/toc_item'},
                       {'title': u'Nobody at home', 'type': '/type/toc_item'},
                       {'title': u'No land like ours',
                        'type': '/type/toc_item'},
                       {'title': u'None shall part us',
                        'type': '/type/toc_item'},
                       {'title': u'Nothing serious',
                        'type': '/type/toc_item'},
                       {'title': u'Now all the bells are ringing',
                        'type': '/type/toc_item'},
                       {'title': u'Now is the month of Maying',
                        'type': '/type/toc_item'},
                       {'title': u'Now the day is over',
                        'type': '/type/toc_item'},
                       {'title': u'O cherish love', 'type': '/type/toc_item'},
                       {'title': u'O give thanks', 'type': '/type/toc_item'},
                       {'title': u'O, I would live in a dairy',
                        'type': '/type/toc_item'},
                       {'title': u'Old folks at home',
                        'type': '/type/toc_item'},
                       {'title': u'O little town of Bethlehem',
                        'type': '/type/toc_item'},
                       {'title': u'The olive tree', 'type': '/type/toc_item'},
                       {'title': u'O lord most holy',
                        'type': '/type/toc_item'},
                       {'title': u'On Canaan shore',
                        'type': '/type/toc_item'},
                       {'title': u'One misty, moisty morning',
                        'type': '/type/toc_item'},
                       {'title': u'Onward, Christian soldiers',
                        'type': '/type/toc_item'},
                       {'title': u'O priase the Lord, our master',
                        'type': '/type/toc_item'},
                       {'title': u'O rest in the Lord',
                        'type': '/type/toc_item'},
                       {'title': u'O star divine', 'type': '/type/toc_item'},
                       {'title': u'Our flag is there',
                        'type': '/type/toc_item'},
                       {'title': u'Our heritage', 'type': '/type/toc_item'},
                       {'title': u'Outward bound', 'type': '/type/toc_item'},
                       {'title': u'O victorious people',
                        'type': '/type/toc_item'},
                       {'title': u'Over the bright blue sea',
                        'type': '/type/toc_item'},
                       {'title': u'O western wind', 'type': '/type/toc_item'},
                       {'title': u'Pack, clouds, away',
                        'type': '/type/toc_item'},
                       {'title': u'The palms', 'type': '/type/toc_item'},
                       {'title': u'The parting hour',
                        'type': '/type/toc_item'},
                       {'title': u'Parting song', 'type': '/type/toc_item'},
                       {'title': u'Pastoral', 'type': '/type/toc_item'},
                       {'title': u'Peace be wtih all',
                        'type': '/type/toc_item'},
                       {'title': u'The pearl', 'type': '/type/toc_item'},
                       {'title': u'A peasant dance',
                        'type': '/type/toc_item'},
                       {'title': u'Petition', 'type': '/type/toc_item'},
                       {'title': u'The Philippines',
                        'type': '/type/toc_item'},
                       {'title': u'Picnics', 'type': '/type/toc_item'},
                       {'title': u"Pilgrims' chorus",
                        'type': '/type/toc_item'},
                       {'title': u'The pioneers', 'type': '/type/toc_item'},
                       {'title': u"Policeman's lot is not a happy one",
                        'type': '/type/toc_item'},
                       {'title': u'Poplar trees', 'type': '/type/toc_item'},
                       {'title': u'Praise', 'type': '/type/toc_item'},
                       {'title': u'Praise God', 'type': '/type/toc_item'},
                       {'title': u'Praise the Lord',
                        'type': '/type/toc_item'},
                       {'title': u'Praise to God and thanks we bring',
                        'type': '/type/toc_item'},
                       {'title': u'A prayer', 'type': '/type/toc_item'},
                       {'title': u'Prayer of Thanksgiving',
                        'type': '/type/toc_item'},
                       {'title': u'Prithee, pretty maiden',
                        'type': '/type/toc_item'},
                       {'title': u'Psalm of the Son of Man',
                        'type': '/type/toc_item'},
                       {'title': u'The range of the buffalo',
                        'type': '/type/toc_item'},
                       {'title': u'The reapers', 'type': '/type/toc_item'},
                       {'title': u'Red, red rose', 'type': '/type/toc_item'},
                       {'title': u'Response', 'type': '/type/toc_item'},
                       {'title': u'Riddle of spring',
                        'type': '/type/toc_item'},
                       {'title': u'The right path', 'type': '/type/toc_item'},
                       {'title': u'Ring on, Chrimstas Bells',
                        'type': '/type/toc_item'},
                       {'title': u'Ring the bells', 'type': '/type/toc_item'},
                       {'title': u'Rise my soul', 'type': '/type/toc_item'},
                       {'title': u'The river', 'type': '/type/toc_item'},
                       {'title': u'The rose', 'type': '/type/toc_item'},
                       {'title': u'Roses', 'type': '/type/toc_item'},
                       {'title': u'A roundel', 'type': '/type/toc_item'},
                       {'title': u'Row the boat', 'type': '/type/toc_item'},
                       {'title': u'Royal summer comes apace',
                        'type': '/type/toc_item'},
                       {'title': u"Sailor's home song",
                        'type': '/type/toc_item'},
                       {'title': u'The sailor lad', 'type': '/type/toc_item'},
                       {'title': u'Salute to the flag',
                        'type': '/type/toc_item'},
                       {'title': u'Sanctus', 'type': '/type/toc_item'},
                       {'title': u'Scotland', 'type': '/type/toc_item'},
                       {'title': u'A sea song', 'type': '/type/toc_item'},
                       {'title': u'Sentence', 'type': '/type/toc_item'},
                       {'title': u'Serenade', 'type': '/type/toc_item'},
                       {'title': u'Shenandoah', 'type': '/type/toc_item'},
                       {'title': u'The sheperhdess',
                        'type': '/type/toc_item'},
                       {'title': u'Shepherd music', 'type': '/type/toc_item'},
                       {'title': u'Silent night', 'type': '/type/toc_item'},
                       {'title': u'Sing on', 'type': '/type/toc_item'},
                       {'title': u'Sleep, baby, sleep',
                        'type': '/type/toc_item'},
                       {'title': u'A song of hope', 'type': '/type/toc_item'},
                       {'title': u'Song of the forge',
                        'type': '/type/toc_item'},
                       {'title': u'A song of thanksgiving',
                        'type': '/type/toc_item'},
                       {'title': u'Song of the night watch',
                        'type': '/type/toc_item'},
                       {'title': u'Song ot the nightingale',
                        'type': '/type/toc_item'},
                       {'title': u'The spacious firmament on high',
                        'type': '/type/toc_item'},
                       {'title': u'Speed our republic',
                        'type': '/type/toc_item'},
                       {'title': u'Spirit of twighlight',
                        'type': '/type/toc_item'},
                       {'title': u'Spring and youth',
                        'type': '/type/toc_item'},
                       {'title': u'Stabat Mater Dolorosa',
                        'type': '/type/toc_item'},
                       {'title': u'Starlight', 'type': '/type/toc_item'},
                       {'title': u'Stars of the summer night',
                        'type': '/type/toc_item'},
                       {'title': u'Star-spangled banner',
                        'type': '/type/toc_item'},
                       {'title': u'Sumer is i-cimen in',
                        'type': '/type/toc_item'},
                       {'title': u'Summer passes', 'type': '/type/toc_item'},
                       {'title': u'The swallow', 'type': '/type/toc_item'},
                       {'title': u'The swan', 'type': '/type/toc_item'},
                       {'title': u'Sweet and low', 'type': '/type/toc_item'},
                       {'title': u'Sweet day is softly dying',
                        'type': '/type/toc_item'},
                       {'title': u'Taken from a county jail',
                        'type': '/type/toc_item'},
                       {'title': u'Take up your sword',
                        'type': '/type/toc_item'},
                       {'title': u'Thanksgiving', 'type': '/type/toc_item'},
                       {'title': u'Thanksgiving Day',
                        'type': '/type/toc_item'},
                       {'title': u'The son of God goes forth to war',
                        'type': '/type/toc_item'},
                       {'title': u"The strife is o'er",
                        'type': '/type/toc_item'},
                       {'title': u'Those evening bells',
                        'type': '/type/toc_item'},
                       {'title': u'Those pals of ours',
                        'type': '/type/toc_item'},
                       {'title': u"Thou'rt lik unto a flower",
                        'type': '/type/toc_item'},
                       {'title': u"Thou'rt like a lovely flower",
                        'type': '/type/toc_item'},
                       {'title': u"thou'rt like unto a flower",
                        'type': '/type/toc_item'},
                       {'title': u'Thou mighty God',
                        'type': '/type/toc_item'},
                       {'title': u'Three children sliding',
                        'type': '/type/toc_item'},
                       {'title': u'Three kings of Orient',
                        'type': '/type/toc_item'},
                       {'title': u'Three little maids from school are we',
                        'type': '/type/toc_item'},
                       {'title': u'Three little tailors',
                        'type': '/type/toc_item'},
                       {'title': u'Three sons', 'type': '/type/toc_item'},
                       {'title': u'Threnody', 'type': '/type/toc_item'},
                       {'title': u'Tit willow', 'type': '/type/toc_item'},
                       {'title': u'The train', 'type': '/type/toc_item'},
                       {'title': u'A tribute', 'type': '/type/toc_item'},
                       {'title': u'The tryst', 'type': '/type/toc_item'},
                       {'title': u'Twighlight', 'type': '/type/toc_item'},
                       {'title': u'Twighlight dreams',
                        'type': '/type/toc_item'},
                       {'title': u'Twighlight music',
                        'type': '/type/toc_item'},
                       {'title': u'Undaunted', 'type': '/type/toc_item'},
                       {'title': u'Under the silver star',
                        'type': '/type/toc_item'},
                       {'title': u'Unfailing love', 'type': '/type/toc_item'},
                       {'title': u'Vale of Cashmere',
                        'type': '/type/toc_item'},
                       {'title': u'Venture Gwen', 'type': '/type/toc_item'},
                       {'title': u'Victors all!', 'type': '/type/toc_item'},
                       {'title': u'The vision', 'type': '/type/toc_item'},
                       {'title': u'The voice of praise',
                        'type': '/type/toc_item'},
                       {'title': u'A voice runs through the sleeping land',
                        'type': '/type/toc_item'},
                       {'title': u'Washington', 'type': '/type/toc_item'},
                       {'title': u'We are dainty little fairies',
                        'type': '/type/toc_item'},
                       {'title': u'Wedding song', 'type': '/type/toc_item'},
                       {'title': u'We sail the ocean blue',
                        'type': '/type/toc_item'},
                       {'title': u'Westminster chimes',
                        'type': '/type/toc_item'},
                       {'title': u'When the foreman bars his steel',
                        'type': '/type/toc_item'},
                       {'title': u'When music leads the way',
                        'type': '/type/toc_item'},
                       {'title': u'When the grand old flag goes by',
                        'type': '/type/toc_item'},
                       {'title': u"Where e'er you walk",
                        'type': '/type/toc_item'},
                       {'title': u'Where honor leads',
                        'type': '/type/toc_item'},
                       {'title': u'The white dove', 'type': '/type/toc_item'},
                       {'title': u"Who's that a-calling?",
                        'type': '/type/toc_item'},
                       {'title': u'Why lingers my gaze',
                        'type': '/type/toc_item'},
                       {'title': u'Winter', 'type': '/type/toc_item'},
                       {'title': u'Winter sport', 'type': '/type/toc_item'},
                       {'title': u'With catlike tread',
                        'type': '/type/toc_item'},
                       {'title': u'Woodland dancing',
                        'type': '/type/toc_item'},
                       {'title': u'Worship', 'type': '/type/toc_item'},
                       {'title': u'The worship of nature',
                        'type': '/type/toc_item'},
                       {'title': u'Ye shepherds, tell me',
                        'type': '/type/toc_item'},
                       {'title': u'Young Colin', 'type': '/type/toc_item'},
                       {'title': u'Youth', 'type': '/type/toc_item'},
                       {'title': u'Yuletide', 'type': '/type/toc_item'}],
 'title': u'Senior Laurel songs for high schools'}),
 ('secretcodeofsucc00stjo_meta.mrc', {'authors': [{'birth_date': u'1967',
              'entity_type': 'person',
              'name': u'St. John, Noah',
              'personal_name': u'St. John, Noah'}],
 'by_statement': u'by Noah St. John ; foreword by Jack Canfield',
 'description': u'Americans spend billions on self-help products, yet few people are living the life they really want. The real problem, says productivity expert Noah St. John, is that most people focus on the "how-to" aspects of success without coming to terms with what calls your "head trash"-the subconscious, emotional roadblocks that prevent people from acting on their real hopes, dreams, and ambitions. St. John has created a seven-step approach that helps you learn how to: eliminate the causes of self-sabotage and fear of success; allow yourself to make more money; remove stress while dramatically increasing personal productivity; improve relationships with coworkers, family, and friends; and experience enhanced feelings of happiness, connection, and love.--From publisher description.',
 'dewey_decimal_class': [u'650.1'],
 'isbn_10': [u'0061715743', u'006176454X'],
 'isbn_13': [u'9780061715747', u'9780061764547'],
 'languages': [{'key': '/languages/eng'}],
 'lc_classification': [u'HF5386 .S7595 2009'],
 'lccn': [u'2008033690'],
 'links': [{'title': u'Table of contents only',
            'url': u'http://www.loc.gov/catdir/toc/ecip0824/2008033690.html'}],
 'notes': u'Includes indexes.',
 'number_of_pages': 243,
 'oclc_number': ['232977651'],
 'pagination': u'xi, 243 p.',
 'publish_country': 'nyu',
 'publish_date': '2009',
 'publish_places': [u'New York'],
 'publishers': [u'HarperCollins Publishers'],
 'subtitle': u'7 hidden steps to more wealth and happiness',
 'table_of_contents': [{'title': u'The secret of success in life and business',
                        'type': '/type/toc_item'},
                       {'title': u"What's wrong with this picture?",
                        'type': '/type/toc_item'},
                       {'title': u"The little assumption that's costing you a fortune",
                        'type': '/type/toc_item'},
                       {'title': u'The secret code revealed',
                        'type': '/type/toc_item'},
                       {'title': u'Step one: afformations',
                        'type': '/type/toc_item'},
                       {'title': u'Step two: loving mirrors and safe havens',
                        'type': '/type/toc_item'},
                       {'title': u'Step three: systems of support',
                        'type': '/type/toc_item'},
                       {'title': u'Step four: goal-free zones and goal replacement surgery',
                        'type': '/type/toc_item'},
                       {'title': u'Step five : who are you trying to protect, punish or please?',
                        'type': '/type/toc_item'},
                       {'title': u'Step six: find your no',
                        'type': '/type/toc_item'},
                       {'title': u'Step seven: find your because',
                        'type': '/type/toc_item'},
                       {'title': u'Now what?', 'type': '/type/toc_item'},
                       {'title': u'Your free bonus gift',
                        'type': '/type/toc_item'},
                       {'title': u'Spread the word.',
                        'type': '/type/toc_item'}],
 'title': u'The secret code of success'}),
 ('uoft_4351105_1626', {'by_statement': u"Nauchno-issledovatel\u02b9ski\u012d institut teorii i istorii izobrazitel'nykh iskusstv",
 'contributions': [u'Ovsi\ufe20a\ufe21nnikov, Mikhail Fedotovich.',
                   u'Akademii\ufe20a\ufe21 khudozhestv SSSR.',
                   u'Institut teorii i istorii izobrazitel\u02b9nykh iskusstv (Akademii\ufe20a\ufe21 khudozhestv SSSR).',
                   u'Nauchno-issledovatel\u02b9ski\u012d institut teorii i istorii izobrazitel\u02b9nykh iskusstv (Rossi\u012dskai\ufe20a\ufe21 akademii\ufe20a\ufe21 khudozhestv).'],
 'languages': [{'key': '/languages/rus'}],
 'lc_classification': [u'BH81 .A55 1962'],
 'notes': u'Includes bibliographical references.',
 'other_titles': [u'Pami\ufe20a\ufe21tniki mirovo\u012d \u0117stetichesko\u012d mysli.'],
 'pagination': u'5 v. :',
 'publish_country': 'ru ',
 'publish_date': '1962',
 'publish_places': [u'Moskva'],
 'publishers': [u'Izd-vo akademii khudozhestv SSSR'],
 'subtitle': u'pami\ufe20a\ufe21tniki mirovo\u012d \u0117stetichesko\u012d mysli',
 'table_of_contents': [{'title': u'T. 1.', 'type': '/type/toc_item'},
                       {'title': u'Antichnost\u02b9 ; Srednie veka ; Vozrozhdenie -- -- t. 2.',
                        'type': '/type/toc_item'},
                       {'title': u'\u0116steticheskie uchenii\ufe20a\ufe21 XVII-XVIII vekov -- -- t. 3.',
                        'type': '/type/toc_item'},
                       {'title': u'\u0116steticheskie uchenii\ufe20a\ufe21 zapadno\u012d Evropy i SSHA (1789-1871).',
                        'type': '/type/toc_item'}],
 'title': u'Istorii\ufe20a\ufe21 \u0117stetiki'}),
 ('warofrebellionco1473unit_meta.mrc', {'authors': [{'entity_type': 'org', 'name': u'United States. War Dept.'}],
 'by_statement': u'prepared under the direction of the Secretary of War',
 'contributions': [u'Scott, Robert N. 1838-1887.',
                   u'Lazelle, Henry Martyn, 1832-',
                   u'Davis, George B. 1847-1914.',
                   u'Perry, Leslie J.',
                   u'Kirkley, Joseph W. 1841-1912.',
                   u'Ainsworth, Frederick Crayton, 1852-1834.',
                   u'Moodey, John Sheldon, 1842-',
                   u'Cowles, Calvin D. 1849- comp.',
                   u'United States. War Records Office.',
                   u'United States. Record and Pension Office.',
                   u'United States. Congress. House.'],
 'languages': [{'key': '/languages/eng'}],
 'lc_classification': [u'E464 .U6'],
 'lccn': [u'03003452'],
 'notes': u'Found also in the House Miscellaneous documents of the 52d to the 56th Congress.\n\nEach number has special index. Inserted in each volume: Additions and corrections ... Washington, Govt. Print. Off., 1902.\n\nSeries 1, v. 1-53, series 3, v. 1-5, and series 4, v. 1-3 include "Alternate designations of organizations mentioned."\n\nVol. 54-55 of series 1 [serial no. 112-113] "have not been published, and no material for them is in hand."  cf. General index, p. xi. Series 2, v. 1 [serial no. 114] with imprint 1894, was not issued until 1898.\n\nEdited in the War Records Office, 1880-July 1899; in the Record and Pension Office, July 1899-1901.\n\nRobert N. Scott compiled and edited v. 1-18, 1880-87, and also collected the greater part of the material for v. 19-36, 1887-91. After his death in 1887 the work was continued by Henry M. Lazelle, 1887-89, and by a board of publication, 1889-99, consisting of George B. Davis, 1889-97, Leslie J. Perry, 1889-99, Joseph W. Kirkley, 1889-99, and Fred C. Ainsworth, 1898-99; from 1899-1901 edited by Fred C. Ainsworth and Joesph W. Kirkley.\n\nSome volumes are 1985 reprints by National Historical Society.\n\n16',
 'number_of_pages': 128,
 'other_titles': [u'Official records of the Union and Confederate Armies.'],
 'pagination': u'70 v. in 128 ;',
 'publish_country': 'dcu',
 'publish_date': '1880',
 'publish_places': [u'Washington'],
 'publishers': [u'Govt. Print. Off.'],
 'subtitle': u'a compilation of the official records of the Union and Confederate armies',
 'title': u'The War of the Rebellion'}),
 ('wrapped_lines', {'authors': [{'entity_type': 'org',
              'name': u'United States. Congress. House. Committee on Foreign Affairs'}],
 'contributions': [u'United States. Congress. House. Committee on Foreign Affairs. Subcommittee on Information and Public Affairs.',
                   u'United States. Congress. House. Committee on Foreign Affairs. Subcommittee on International Organizations and Movements',
                   u'United States. Congress. House. Committee on Foreign Affairs. Subcommittee on Europe'],
 'description': u"Contains transcripts of House Foreign Relations Committee executive session hearings. Transcribed hearings are. a. Mutual Defense Assistance Control Act of 1951. Mar. 5, 9, 15, 20, Apr. 3, 5, 1951. p. 2-248. Includes discussions of Allied policy coordination on east-west trade and of economic sanctions impact on Soviet and Eastern European economies. b. U.S. information programs abroad. Mar. 19, 1951, Feb. 20, 1952. p. 258-288, 303-326. Includes discussions of Voice of America operations and of Soviet propaganda program. c. U.N. admission policies and charter revision. Mar. 21, 1951. d. Refugees from Eastern Europe. Mar. 5, 1952, Mar. 11, 1953. p. 327-349, 431-457. Includes discussions of emigration through East Berlin, East German border security measures, and U.S. program to recruit East European refugees for a special military unit. e. Briefing on U.S. disarmament proposals to U.N. May 27, 1952. p. 351-367. Includes discussion of Soviet arms reduction negotiating positions. f. Briefing on Korean War and Indochina affairs. Jan. 22, 1953. p. 369-388. Includes discussions on upcoming trip to Europe by Secretary of State John Foster Dulles and issues relating to administration of the State Dept. g. Resolution to repudiate wartime agreements with the Soviet Union and to protest Soviet subjugation of Eastern Europe and Far Eastern nations. Feb. 26, 1953. p. 389-435. h. Briefing on impact of Stalin's death on Soviet foreign and domestic policies. Apr. 24, 1953. p. 459-490. Includes discussion of Soviet anti-American propaganda efforts. Classified material has been deleted. i. Condemnation of Soviet Union suppression of East Berlin workers' uprising and subjugation of other nations. July 15, 19, 1953. p. 491-523. Includes discussion of reunification of Germany. j. Briefing on East German affairs. July 30, 1953. p. 525-536. Includes discussion of West German neo-Nazi movements. k. Foreign aid mutual security programs. Jan. 27, 1954. p. 537-567. l. Briefing on U.S. negotiating positions on GATT and Mutual Defense Assistance Control Act effectiveness. Jan. 19, 1954. p. 569-588. m. Meeting with Polish government-in-exile Foreign Minister Adam Ciolkosz and Representative in D.C. Jerzy Lerski. Jan. 28, 1954. p. 589-605. Includes discussion of German rearmament.\n\nConsiders (82) H.R. 1621, (82) H.R. 1939, (82) H.R. 4550, (82) H.R. 3518, (83) H. Res. 172, (83) H. Res. 200, (83) H.J. Res. 200, (83) H. Con. Res. 122, (83) H. Con. Res. 123, (83) H. Con. Res. 125, (83) H. Con. Res. 158, (83) H. Con. Res. 36.",
 'languages': [{'key': '/languages/eng'}],
 'location': [u'BIN'],
 'notes': u'"[pub. 1980.]."\n\nRecord is based on bibliographic data in CIS US Congressional Committee Hearings Index. Reuse except for individual research requires license from Congressional Information Service, Inc.\n\nIndexed in CIS US Congressional Committee Hearings Index Part V\n\nMicrofiche. [Bethesda, Md.] : Congressional Information Service 1983. 11 x 15 cm.',
 'number_of_pages': 605,
 'oclc_number': [u'10504687'],
 'pagination': u'xvii, 605 p.',
 'physical_format': u'[microform] :',
 'publish_country': 'mdu',
 'publish_date': '1983',
 'publish_places': [u'Washington'],
 'publishers': [u'U.S. G.P.O.'],
 'subtitle': u'hearings before the United States House Committee on Foreign Affairs, Subcommittee on H.R. 1621 and H.R. 1939, Subcommittee on Information and Public Affairs, Subcommittee on International Organizations and Movements, Subcommittee on Europe, Eighty-Second Congress, first session and Eighty-Second Congress, second session and Eighty-Third Congress, first session and Eighty-Third Congress, second session',
 'title': u'Selected Executive Session Hearings of the Committee, 1951-56; Volume XIV: U.S. Foreign Policy and the East-West Confrontation'}),
 ('wwu_51323556', {'by_statement': u'edited by  Michael F. Goodchild, Donald G. Janelle',
 'contributions': [u'Goodchild, Michael F.', u'Janelle, Donald G., 1940-'],
 'isbn_10': [u'0195152700'],
 'isbn_13': [u'9780195152708'],
 'languages': [{'key': '/languages/eng'}],
 'lc_classification': [u'HA30.6 .S665 2004'],
 'lccn': [u'2002156669'],
 'links': [{'title': u'Publisher description',
            'url': u'http://www.loc.gov/catdir/enhancements/fy0613/2002156669-d.html'}],
 'notes': u'Includes bibliographical references and index.\n\nGift; James Loucky; May, 2007.\n\n"Gift, May 2007"',
 'number_of_pages': 456,
 'oclc_number': ['51323556'],
 'pagination': u'xviii, 456 p. :',
 'publish_country': 'enk',
 'publish_date': '2004',
 'publish_places': [u'Oxford [England]', u'New York'],
 'publishers': [u'Oxford University Press'],
 'series': [u'Spatial information systems'],
 'table_of_contents': [{'title': u'Introduction. Thinking spatially in the social sciences',
                        'type': '/type/toc_item'},
                       {'title': u'Michael F. Goodchild and Donald G. Janelle -- Spatial analysis at individual and household levels. Inferring the behavior of households from remotely sensed changes in land cover : current methods and future directions',
                        'type': '/type/toc_item'},
                       {'title': u'Bruce Boucek and Emilio F. Moran. Geo-visualization of human activity patterns using 3-d GIS : a time-geographic approach',
                        'type': '/type/toc_item'},
                       {'title': u'Mei-Po Kwan and Jiyeong Lee. Agent-based modeling : from individual residential choice to urban residential dynamics',
                        'type': '/type/toc_item'},
                       {'title': u'Itzhak Benenson. Too much of the wrong kind of data : implications for the practice of micro-scale spatial modeling',
                        'type': '/type/toc_item'},
                       {'title': u"David O'Sullivan. Neighborhood-level analysis. Identifying ethnic neighborhoods with census data : group concentration and spatial clustering",
                        'type': '/type/toc_item'},
                       {'title': u'John R. Logan and Wenquan Zhang. Spatial analyses of homicide with areal data',
                        'type': '/type/toc_item'},
                       {'title': u'Steven F. Messner and Luc Anselin. Spatial (dis)advantage and homicide in Chicago neighborhoods',
                        'type': '/type/toc_item'},
                       {'title': u'Robert J. Sampson and Jeffrey D. Morenoff. Measuring spatial diffusion of shots fired activity across city neighborhoods',
                        'type': '/type/toc_item'},
                       {'title': u'Jacqueline Cohen and George Tita. The spatial structure of urban political discussion networks',
                        'type': '/type/toc_item'},
                       {'title': u'Munroe Eagles, Paul B\xe9langer, and Hugh W. Calkins. Region-level analysis. Mapping social exclusion and inclusion in developing countries : spatial patterns of S\xe0o Paulo in the 1990s',
                        'type': '/type/toc_item'},
                       {'title': u'Gilberto C\u01cemara, Aldaiza Sposati, Dirce Koga, Antonio Miguel Monteiro, Frederico Roman Ramos, Eduardo Camargo, and Suzana Druck Fuks. Business location and spatial externalities : tying concepts to measures',
                        'type': '/type/toc_item'},
                       {'title': u'Stuart H Sweeney and Edward J. Feser. Updating spatial perspectives and analytical frameworks in urban research',
                        'type': '/type/toc_item'},
                       {'title': u'Qing Shen. Spatial analysis of regional income inequality',
                        'type': '/type/toc_item'},
                       {'title': u'Sergio J. Rey. Shaping policy decisions with spatial analysis',
                        'type': '/type/toc_item'},
                       {'title': u'Ted K. Bradshaw and Brian Muller. Geographical approaches for reconstructing past human behavior from prehistoric roadways',
                        'type': '/type/toc_item'},
                       {'title': u'John Kantner. Multi-scale spatial perspectives. Time, space, and archaeological landscapes : establishing connections in the first millennium BC',
                        'type': '/type/toc_item'},
                       {'title': u'Patrick Daly and Gary Lock. Spatial perspectives in public health',
                        'type': '/type/toc_item'},
                       {'title': u'Anthony C. Gatrell and Janette E. Rigby. The role of spatial analysis in demographic research',
                        'type': '/type/toc_item'},
                       {'title': u'John R. Weeks. Spatial interaction models of international telecommunication flows',
                        'type': '/type/toc_item'},
                       {'title': u'Jean-Michel Guldmann. Planning scenario visualization and assessment : a cellular automata based integrated spatial decision support system',
                        'type': '/type/toc_item'},
                       {'title': u'Roger White, Bas Straatman, and Guy Engelen.',
                        'type': '/type/toc_item'}],
 'title': u'Spatially integrated social science'}),
 ('zweibchersatir01horauoft_meta.mrc', {'authors': [{'entity_type': 'person',
              'name': u'Horace.',
              'personal_name': u'Horace.'}],
 'by_statement': u'aus dreissig unverglichenen und allen bisher verglichenen Handschriften, wie auch s\xc3\xa4mmtlichen bedeutenden Ausgaben kritisch hergestellt, metrisch \xc3\xbcbersetzt, und mit erkl\xc3\xa4rendem Commentar versehen von C. Kirchner',
 'contributions': [u'26\x1e10 Kirchner, Carl Christian Jacob, 1787-1855, tr. [and] ed.',
                   u'Teuffel, Wilhelm Sigmund, 1820-1878,'],
 'languages': [{'key': '/languages/ger'}],
 'notes': u'26',
 'pagination': u'2 vol. in 3.',
 'publish_country': 'ge ',
 'publish_date': '1854',
 'publish_places': [u'Leipzig'],
 'publishers': [u'Teubner'],
 'table_of_contents': [{'title': u'Vol. 1. Text, \xc3\x9cbersetzung und kritischer Apparat.-  Vol. 2, pt. 1, Commentar zum ersten Buche der Satiren.-  Vol. 2, pt. 2, Commentar zum zweiten Buche der Satiren, verfasst von W.S. Teuffel.',
                        'type': '/type/toc_item'}],
 'title': u'Zwei B\xc3\xbccher Satiren',
 'work_titles': [u'Satirae']}),
('talis_two_authors.mrc',
 {'authors': [{'entity_type': 'person',
               'name': u'Dowling, James Walter Frederick.',
               'personal_name': u'Dowling, James Walter Frederick.'},
              {'entity_type': 'event',
               'name': u'Conference on Civil Engineering Problems Overseas.'}],
  'by_statement': u'[by] J.W.F. Dowling, F.H.P. Williams',
  'contributions': [u'Williams, Frederik Harry Paston.',
                    u'Conference on Civil Engineering Problems Overseas (1964)'],
  'languages': [{'key': '/languages/eng'}],
  'notes': u'Paper from Conference on Civil Engineering problems Overseas, 1964.',
  'pagination': u'1 vol',
  'publish_country': 'xxk',
  'publish_date': '1964',
  'publishers': [u'Institution of Civil Engineers'],
  'title': u'The use of aerial photographs in materialssurveys and classification of landforms'}),
('talis_no_title.mrc', {
    'publishers': [u'Methuen'],
    'table_of_contents': [{'type': '/type/toc_item', 'title': u'Contents:The Old batchelour, - -The double dealer.'}],
    'title': u'Plays.',
    'dewey_decimal_class': [u'822.4'],
    'languages': [{'key': '/languages/eng'}],
    'publish_date': '1895',
    'publish_country': 'xxk',
    'authors': [{'birth_date': u'1670', 'personal_name': u'Congreve, William', 'death_date': u'1729', 'name': u'Congreve, William', 'entity_type': 'person'}],
    'publish_places': [u'London'],
}),
('talis_740.mrc', {
    'other_titles': [u'Modern Supreme Court.'],
    'publishers': [u'Harvard U.P.'],
    'pagination': u'D8.390. n.e.',
    'table_of_contents': [{'type': '/type/toc_item', 'title': u'The modern Supreme Court /.'}],
    'title': u'Modern Supreme Court',
    'number_of_pages': 390,
    'languages': [{'key': '/languages/eng'}],
    'isbn_10': [u'0674580567'],
    'publish_date': '1973',
    'publish_country': 'xxk',
    'authors': [{'personal_name': u'McCloskey, Robert Green.', 'name': u'McCloskey, Robert Green.', 'entity_type': 'person'}], 
    'publish_places': [u'Cambridge,Mass', u'London']}),
('talis_245p.mrc', {'languages': [{'key': '/languages/eng'}], 'publishers': [u'Cambridge University Press'], 'isbn_10': [u'0521282047'], 'publish_date': '1981', 'publish_country': 'xxk', 'title': u'SMP topic mathematics', 'subtitle': 'Pattern and design', 'publish_places': [u'Cambridge (etc.)'], 'authors': [{'name': u'School Mathematics Project.', 'entity_type': 'org'}]}),
]

class TestParse(unittest.TestCase):
    def test_xml(self):
        for i, j in xml_samples:
            f = open('test_data/' + i + '_marc.xml')
            element = etree.parse(f).getroot()
            if element.tag != record_tag and element[0].tag == record_tag:
                element = element[0]
            rec = MarcXml(element)
            edition_marc_xml = read_edition(rec)
            self.assertEqual(edition_marc_xml, j)

    def test_binary(self):
        for i, j in bin_samples:
            f = open('test_data/' + i)
            rec = MarcBinary(f.read())
            edition_marc_bin = read_edition(rec)
            self.assertEqual(edition_marc_bin, j)

        i = 'talis_see_also.mrc'
        f = open('test_data/' + i)
        rec = MarcBinary(f.read())
        self.assertRaises(SeeAlsoAsTitle, read_edition, rec)

        i = 'talis_no_title2.mrc'
        f = open('test_data/' + i)
        rec = MarcBinary(f.read())
        self.assertRaises(NoTitle, read_edition, rec)
